/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as StreamProxyRouteImport } from './routes/stream-proxy'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/_dashboard'
import { Route as AuthedDashboardConfigRouteRouteImport } from './routes/_authed/_dashboard/config/route'
import { Route as AuthedDashboardSessionsIndexRouteImport } from './routes/_authed/_dashboard/sessions/index'
import { Route as AuthedDashboardPlayerIndexRouteImport } from './routes/_authed/_dashboard/player/index'
import { Route as AuthedDashboardPipelineIndexRouteImport } from './routes/_authed/_dashboard/pipeline/index'
import { Route as AuthedDashboardPipelineJobsIndexRouteImport } from './routes/_authed/_dashboard/pipeline/jobs/index'

const AuthedChangePasswordLazyRouteImport = createFileRoute(
  '/_authed/change-password',
)()
const AuthedDashboardDashboardLazyRouteImport = createFileRoute(
  '/_authed/_dashboard/dashboard',
)()
const AuthedDashboardStreamersIndexLazyRouteImport = createFileRoute(
  '/_authed/_dashboard/streamers/',
)()
const AuthedDashboardNotificationsIndexLazyRouteImport = createFileRoute(
  '/_authed/_dashboard/notifications/',
)()
const AuthedDashboardSystemHealthLazyRouteImport = createFileRoute(
  '/_authed/_dashboard/system/health',
)()
const AuthedDashboardStreamersNewLazyRouteImport = createFileRoute(
  '/_authed/_dashboard/streamers/new',
)()
const AuthedDashboardSessionsSessionIdLazyRouteImport = createFileRoute(
  '/_authed/_dashboard/sessions/$sessionId',
)()
const AuthedDashboardPipelineOutputsLazyRouteImport = createFileRoute(
  '/_authed/_dashboard/pipeline/outputs',
)()
const AuthedDashboardNotificationsEventsLazyRouteImport = createFileRoute(
  '/_authed/_dashboard/notifications/events',
)()
const AuthedDashboardConfigThemeLazyRouteImport = createFileRoute(
  '/_authed/_dashboard/config/theme',
)()
const AuthedDashboardConfigLoggingLazyRouteImport = createFileRoute(
  '/_authed/_dashboard/config/logging',
)()
const AuthedDashboardConfigLanguageLazyRouteImport = createFileRoute(
  '/_authed/_dashboard/config/language',
)()
const AuthedDashboardConfigGlobalLazyRouteImport = createFileRoute(
  '/_authed/_dashboard/config/global',
)()
const AuthedDashboardConfigBackupLazyRouteImport = createFileRoute(
  '/_authed/_dashboard/config/backup',
)()
const AuthedDashboardPipelineWorkflowsIndexLazyRouteImport = createFileRoute(
  '/_authed/_dashboard/pipeline/workflows/',
)()
const AuthedDashboardPipelinePresetsIndexLazyRouteImport = createFileRoute(
  '/_authed/_dashboard/pipeline/presets/',
)()
const AuthedDashboardConfigTemplatesIndexLazyRouteImport = createFileRoute(
  '/_authed/_dashboard/config/templates/',
)()
const AuthedDashboardConfigPlatformsIndexLazyRouteImport = createFileRoute(
  '/_authed/_dashboard/config/platforms/',
)()
const AuthedDashboardConfigEnginesIndexLazyRouteImport = createFileRoute(
  '/_authed/_dashboard/config/engines/',
)()
const AuthedDashboardStreamersIdEditLazyRouteImport = createFileRoute(
  '/_authed/_dashboard/streamers/$id/edit',
)()
const AuthedDashboardPipelineWorkflowsCreateLazyRouteImport = createFileRoute(
  '/_authed/_dashboard/pipeline/workflows/create',
)()
const AuthedDashboardPipelineWorkflowsWorkflowIdLazyRouteImport =
  createFileRoute('/_authed/_dashboard/pipeline/workflows/$workflowId')()
const AuthedDashboardPipelinePresetsCreateLazyRouteImport = createFileRoute(
  '/_authed/_dashboard/pipeline/presets/create',
)()
const AuthedDashboardPipelinePresetsPresetIdLazyRouteImport = createFileRoute(
  '/_authed/_dashboard/pipeline/presets/$presetId',
)()
const AuthedDashboardPipelineJobsNewLazyRouteImport = createFileRoute(
  '/_authed/_dashboard/pipeline/jobs/new',
)()
const AuthedDashboardPipelineJobsJobIdLazyRouteImport = createFileRoute(
  '/_authed/_dashboard/pipeline/jobs/$jobId',
)()
const AuthedDashboardPipelineExecutionsPipelineIdLazyRouteImport =
  createFileRoute('/_authed/_dashboard/pipeline/executions/$pipelineId')()
const AuthedDashboardConfigTemplatesCreateLazyRouteImport = createFileRoute(
  '/_authed/_dashboard/config/templates/create',
)()
const AuthedDashboardConfigTemplatesTemplateIdLazyRouteImport = createFileRoute(
  '/_authed/_dashboard/config/templates/$templateId',
)()
const AuthedDashboardConfigPlatformsPlatformIdLazyRouteImport = createFileRoute(
  '/_authed/_dashboard/config/platforms/$platformId',
)()
const AuthedDashboardConfigEnginesCreateLazyRouteImport = createFileRoute(
  '/_authed/_dashboard/config/engines/create',
)()
const AuthedDashboardConfigEnginesEngineIdLazyRouteImport = createFileRoute(
  '/_authed/_dashboard/config/engines/$engineId',
)()

const StreamProxyRoute = StreamProxyRouteImport.update({
  id: '/stream-proxy',
  path: '/stream-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedChangePasswordLazyRoute =
  AuthedChangePasswordLazyRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthedRoute,
  } as any).lazy(() =>
    import('./routes/_authed/change-password.lazy').then((d) => d.Route),
  )
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any).lazy(() => import('./routes/_public/login.lazy').then((d) => d.Route))
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardDashboardLazyRoute =
  AuthedDashboardDashboardLazyRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/dashboard.lazy').then((d) => d.Route),
  )
const AuthedDashboardConfigRouteRoute =
  AuthedDashboardConfigRouteRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => AuthedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/config/route.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardStreamersIndexLazyRoute =
  AuthedDashboardStreamersIndexLazyRouteImport.update({
    id: '/streamers/',
    path: '/streamers/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/streamers/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardNotificationsIndexLazyRoute =
  AuthedDashboardNotificationsIndexLazyRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/notifications/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardSessionsIndexRoute =
  AuthedDashboardSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/sessions/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardPlayerIndexRoute =
  AuthedDashboardPlayerIndexRouteImport.update({
    id: '/player/',
    path: '/player/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/player/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardPipelineIndexRoute =
  AuthedDashboardPipelineIndexRouteImport.update({
    id: '/pipeline/',
    path: '/pipeline/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardSystemHealthLazyRoute =
  AuthedDashboardSystemHealthLazyRouteImport.update({
    id: '/system/health',
    path: '/system/health',
    getParentRoute: () => AuthedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/system/health.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardStreamersNewLazyRoute =
  AuthedDashboardStreamersNewLazyRouteImport.update({
    id: '/streamers/new',
    path: '/streamers/new',
    getParentRoute: () => AuthedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/streamers/new.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardSessionsSessionIdLazyRoute =
  AuthedDashboardSessionsSessionIdLazyRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => AuthedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/sessions/$sessionId.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardPipelineOutputsLazyRoute =
  AuthedDashboardPipelineOutputsLazyRouteImport.update({
    id: '/pipeline/outputs',
    path: '/pipeline/outputs',
    getParentRoute: () => AuthedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/pipeline/outputs.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardNotificationsEventsLazyRoute =
  AuthedDashboardNotificationsEventsLazyRouteImport.update({
    id: '/notifications/events',
    path: '/notifications/events',
    getParentRoute: () => AuthedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/notifications/events.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardConfigThemeLazyRoute =
  AuthedDashboardConfigThemeLazyRouteImport.update({
    id: '/theme',
    path: '/theme',
    getParentRoute: () => AuthedDashboardConfigRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/config/theme.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardConfigLoggingLazyRoute =
  AuthedDashboardConfigLoggingLazyRouteImport.update({
    id: '/logging',
    path: '/logging',
    getParentRoute: () => AuthedDashboardConfigRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/config/logging.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardConfigLanguageLazyRoute =
  AuthedDashboardConfigLanguageLazyRouteImport.update({
    id: '/language',
    path: '/language',
    getParentRoute: () => AuthedDashboardConfigRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/config/language.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardConfigGlobalLazyRoute =
  AuthedDashboardConfigGlobalLazyRouteImport.update({
    id: '/global',
    path: '/global',
    getParentRoute: () => AuthedDashboardConfigRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/config/global.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardConfigBackupLazyRoute =
  AuthedDashboardConfigBackupLazyRouteImport.update({
    id: '/backup',
    path: '/backup',
    getParentRoute: () => AuthedDashboardConfigRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/config/backup.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardPipelineWorkflowsIndexLazyRoute =
  AuthedDashboardPipelineWorkflowsIndexLazyRouteImport.update({
    id: '/pipeline/workflows/',
    path: '/pipeline/workflows/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/pipeline/workflows/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardPipelinePresetsIndexLazyRoute =
  AuthedDashboardPipelinePresetsIndexLazyRouteImport.update({
    id: '/pipeline/presets/',
    path: '/pipeline/presets/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/pipeline/presets/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardConfigTemplatesIndexLazyRoute =
  AuthedDashboardConfigTemplatesIndexLazyRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthedDashboardConfigRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/config/templates/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardConfigPlatformsIndexLazyRoute =
  AuthedDashboardConfigPlatformsIndexLazyRouteImport.update({
    id: '/platforms/',
    path: '/platforms/',
    getParentRoute: () => AuthedDashboardConfigRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/config/platforms/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardConfigEnginesIndexLazyRoute =
  AuthedDashboardConfigEnginesIndexLazyRouteImport.update({
    id: '/engines/',
    path: '/engines/',
    getParentRoute: () => AuthedDashboardConfigRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/config/engines/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardPipelineJobsIndexRoute =
  AuthedDashboardPipelineJobsIndexRouteImport.update({
    id: '/pipeline/jobs/',
    path: '/pipeline/jobs/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/pipeline/jobs/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardStreamersIdEditLazyRoute =
  AuthedDashboardStreamersIdEditLazyRouteImport.update({
    id: '/streamers/$id/edit',
    path: '/streamers/$id/edit',
    getParentRoute: () => AuthedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/streamers/$id.edit.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardPipelineWorkflowsCreateLazyRoute =
  AuthedDashboardPipelineWorkflowsCreateLazyRouteImport.update({
    id: '/pipeline/workflows/create',
    path: '/pipeline/workflows/create',
    getParentRoute: () => AuthedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/pipeline/workflows/create.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardPipelineWorkflowsWorkflowIdLazyRoute =
  AuthedDashboardPipelineWorkflowsWorkflowIdLazyRouteImport.update({
    id: '/pipeline/workflows/$workflowId',
    path: '/pipeline/workflows/$workflowId',
    getParentRoute: () => AuthedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/pipeline/workflows/$workflowId.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardPipelinePresetsCreateLazyRoute =
  AuthedDashboardPipelinePresetsCreateLazyRouteImport.update({
    id: '/pipeline/presets/create',
    path: '/pipeline/presets/create',
    getParentRoute: () => AuthedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/pipeline/presets/create.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardPipelinePresetsPresetIdLazyRoute =
  AuthedDashboardPipelinePresetsPresetIdLazyRouteImport.update({
    id: '/pipeline/presets/$presetId',
    path: '/pipeline/presets/$presetId',
    getParentRoute: () => AuthedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/pipeline/presets/$presetId.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardPipelineJobsNewLazyRoute =
  AuthedDashboardPipelineJobsNewLazyRouteImport.update({
    id: '/pipeline/jobs/new',
    path: '/pipeline/jobs/new',
    getParentRoute: () => AuthedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/pipeline/jobs/new.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardPipelineJobsJobIdLazyRoute =
  AuthedDashboardPipelineJobsJobIdLazyRouteImport.update({
    id: '/pipeline/jobs/$jobId',
    path: '/pipeline/jobs/$jobId',
    getParentRoute: () => AuthedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/pipeline/jobs/$jobId.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardPipelineExecutionsPipelineIdLazyRoute =
  AuthedDashboardPipelineExecutionsPipelineIdLazyRouteImport.update({
    id: '/pipeline/executions/$pipelineId',
    path: '/pipeline/executions/$pipelineId',
    getParentRoute: () => AuthedDashboardRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/pipeline/executions.$pipelineId.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardConfigTemplatesCreateLazyRoute =
  AuthedDashboardConfigTemplatesCreateLazyRouteImport.update({
    id: '/templates/create',
    path: '/templates/create',
    getParentRoute: () => AuthedDashboardConfigRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/config/templates/create.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardConfigTemplatesTemplateIdLazyRoute =
  AuthedDashboardConfigTemplatesTemplateIdLazyRouteImport.update({
    id: '/templates/$templateId',
    path: '/templates/$templateId',
    getParentRoute: () => AuthedDashboardConfigRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/config/templates/$templateId.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardConfigPlatformsPlatformIdLazyRoute =
  AuthedDashboardConfigPlatformsPlatformIdLazyRouteImport.update({
    id: '/platforms/$platformId',
    path: '/platforms/$platformId',
    getParentRoute: () => AuthedDashboardConfigRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/config/platforms/$platformId.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardConfigEnginesCreateLazyRoute =
  AuthedDashboardConfigEnginesCreateLazyRouteImport.update({
    id: '/engines/create',
    path: '/engines/create',
    getParentRoute: () => AuthedDashboardConfigRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/config/engines/create.lazy').then(
      (d) => d.Route,
    ),
  )
const AuthedDashboardConfigEnginesEngineIdLazyRoute =
  AuthedDashboardConfigEnginesEngineIdLazyRouteImport.update({
    id: '/engines/$engineId',
    path: '/engines/$engineId',
    getParentRoute: () => AuthedDashboardConfigRouteRoute,
  } as any).lazy(() =>
    import('./routes/_authed/_dashboard/config/engines/$engineId.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/stream-proxy': typeof StreamProxyRoute
  '/login': typeof PublicLoginRoute
  '/change-password': typeof AuthedChangePasswordLazyRoute
  '/config': typeof AuthedDashboardConfigRouteRouteWithChildren
  '/dashboard': typeof AuthedDashboardDashboardLazyRoute
  '/config/backup': typeof AuthedDashboardConfigBackupLazyRoute
  '/config/global': typeof AuthedDashboardConfigGlobalLazyRoute
  '/config/language': typeof AuthedDashboardConfigLanguageLazyRoute
  '/config/logging': typeof AuthedDashboardConfigLoggingLazyRoute
  '/config/theme': typeof AuthedDashboardConfigThemeLazyRoute
  '/notifications/events': typeof AuthedDashboardNotificationsEventsLazyRoute
  '/pipeline/outputs': typeof AuthedDashboardPipelineOutputsLazyRoute
  '/sessions/$sessionId': typeof AuthedDashboardSessionsSessionIdLazyRoute
  '/streamers/new': typeof AuthedDashboardStreamersNewLazyRoute
  '/system/health': typeof AuthedDashboardSystemHealthLazyRoute
  '/pipeline/': typeof AuthedDashboardPipelineIndexRoute
  '/player/': typeof AuthedDashboardPlayerIndexRoute
  '/sessions/': typeof AuthedDashboardSessionsIndexRoute
  '/notifications/': typeof AuthedDashboardNotificationsIndexLazyRoute
  '/streamers/': typeof AuthedDashboardStreamersIndexLazyRoute
  '/config/engines/$engineId': typeof AuthedDashboardConfigEnginesEngineIdLazyRoute
  '/config/engines/create': typeof AuthedDashboardConfigEnginesCreateLazyRoute
  '/config/platforms/$platformId': typeof AuthedDashboardConfigPlatformsPlatformIdLazyRoute
  '/config/templates/$templateId': typeof AuthedDashboardConfigTemplatesTemplateIdLazyRoute
  '/config/templates/create': typeof AuthedDashboardConfigTemplatesCreateLazyRoute
  '/pipeline/executions/$pipelineId': typeof AuthedDashboardPipelineExecutionsPipelineIdLazyRoute
  '/pipeline/jobs/$jobId': typeof AuthedDashboardPipelineJobsJobIdLazyRoute
  '/pipeline/jobs/new': typeof AuthedDashboardPipelineJobsNewLazyRoute
  '/pipeline/presets/$presetId': typeof AuthedDashboardPipelinePresetsPresetIdLazyRoute
  '/pipeline/presets/create': typeof AuthedDashboardPipelinePresetsCreateLazyRoute
  '/pipeline/workflows/$workflowId': typeof AuthedDashboardPipelineWorkflowsWorkflowIdLazyRoute
  '/pipeline/workflows/create': typeof AuthedDashboardPipelineWorkflowsCreateLazyRoute
  '/streamers/$id/edit': typeof AuthedDashboardStreamersIdEditLazyRoute
  '/pipeline/jobs/': typeof AuthedDashboardPipelineJobsIndexRoute
  '/config/engines/': typeof AuthedDashboardConfigEnginesIndexLazyRoute
  '/config/platforms/': typeof AuthedDashboardConfigPlatformsIndexLazyRoute
  '/config/templates/': typeof AuthedDashboardConfigTemplatesIndexLazyRoute
  '/pipeline/presets/': typeof AuthedDashboardPipelinePresetsIndexLazyRoute
  '/pipeline/workflows/': typeof AuthedDashboardPipelineWorkflowsIndexLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/stream-proxy': typeof StreamProxyRoute
  '/login': typeof PublicLoginRoute
  '/change-password': typeof AuthedChangePasswordLazyRoute
  '/config': typeof AuthedDashboardConfigRouteRouteWithChildren
  '/dashboard': typeof AuthedDashboardDashboardLazyRoute
  '/config/backup': typeof AuthedDashboardConfigBackupLazyRoute
  '/config/global': typeof AuthedDashboardConfigGlobalLazyRoute
  '/config/language': typeof AuthedDashboardConfigLanguageLazyRoute
  '/config/logging': typeof AuthedDashboardConfigLoggingLazyRoute
  '/config/theme': typeof AuthedDashboardConfigThemeLazyRoute
  '/notifications/events': typeof AuthedDashboardNotificationsEventsLazyRoute
  '/pipeline/outputs': typeof AuthedDashboardPipelineOutputsLazyRoute
  '/sessions/$sessionId': typeof AuthedDashboardSessionsSessionIdLazyRoute
  '/streamers/new': typeof AuthedDashboardStreamersNewLazyRoute
  '/system/health': typeof AuthedDashboardSystemHealthLazyRoute
  '/pipeline': typeof AuthedDashboardPipelineIndexRoute
  '/player': typeof AuthedDashboardPlayerIndexRoute
  '/sessions': typeof AuthedDashboardSessionsIndexRoute
  '/notifications': typeof AuthedDashboardNotificationsIndexLazyRoute
  '/streamers': typeof AuthedDashboardStreamersIndexLazyRoute
  '/config/engines/$engineId': typeof AuthedDashboardConfigEnginesEngineIdLazyRoute
  '/config/engines/create': typeof AuthedDashboardConfigEnginesCreateLazyRoute
  '/config/platforms/$platformId': typeof AuthedDashboardConfigPlatformsPlatformIdLazyRoute
  '/config/templates/$templateId': typeof AuthedDashboardConfigTemplatesTemplateIdLazyRoute
  '/config/templates/create': typeof AuthedDashboardConfigTemplatesCreateLazyRoute
  '/pipeline/executions/$pipelineId': typeof AuthedDashboardPipelineExecutionsPipelineIdLazyRoute
  '/pipeline/jobs/$jobId': typeof AuthedDashboardPipelineJobsJobIdLazyRoute
  '/pipeline/jobs/new': typeof AuthedDashboardPipelineJobsNewLazyRoute
  '/pipeline/presets/$presetId': typeof AuthedDashboardPipelinePresetsPresetIdLazyRoute
  '/pipeline/presets/create': typeof AuthedDashboardPipelinePresetsCreateLazyRoute
  '/pipeline/workflows/$workflowId': typeof AuthedDashboardPipelineWorkflowsWorkflowIdLazyRoute
  '/pipeline/workflows/create': typeof AuthedDashboardPipelineWorkflowsCreateLazyRoute
  '/streamers/$id/edit': typeof AuthedDashboardStreamersIdEditLazyRoute
  '/pipeline/jobs': typeof AuthedDashboardPipelineJobsIndexRoute
  '/config/engines': typeof AuthedDashboardConfigEnginesIndexLazyRoute
  '/config/platforms': typeof AuthedDashboardConfigPlatformsIndexLazyRoute
  '/config/templates': typeof AuthedDashboardConfigTemplatesIndexLazyRoute
  '/pipeline/presets': typeof AuthedDashboardPipelinePresetsIndexLazyRoute
  '/pipeline/workflows': typeof AuthedDashboardPipelineWorkflowsIndexLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/logout': typeof LogoutRoute
  '/stream-proxy': typeof StreamProxyRoute
  '/_authed/_dashboard': typeof AuthedDashboardRouteWithChildren
  '/_public/login': typeof PublicLoginRoute
  '/_authed/change-password': typeof AuthedChangePasswordLazyRoute
  '/_authed/_dashboard/config': typeof AuthedDashboardConfigRouteRouteWithChildren
  '/_authed/_dashboard/dashboard': typeof AuthedDashboardDashboardLazyRoute
  '/_authed/_dashboard/config/backup': typeof AuthedDashboardConfigBackupLazyRoute
  '/_authed/_dashboard/config/global': typeof AuthedDashboardConfigGlobalLazyRoute
  '/_authed/_dashboard/config/language': typeof AuthedDashboardConfigLanguageLazyRoute
  '/_authed/_dashboard/config/logging': typeof AuthedDashboardConfigLoggingLazyRoute
  '/_authed/_dashboard/config/theme': typeof AuthedDashboardConfigThemeLazyRoute
  '/_authed/_dashboard/notifications/events': typeof AuthedDashboardNotificationsEventsLazyRoute
  '/_authed/_dashboard/pipeline/outputs': typeof AuthedDashboardPipelineOutputsLazyRoute
  '/_authed/_dashboard/sessions/$sessionId': typeof AuthedDashboardSessionsSessionIdLazyRoute
  '/_authed/_dashboard/streamers/new': typeof AuthedDashboardStreamersNewLazyRoute
  '/_authed/_dashboard/system/health': typeof AuthedDashboardSystemHealthLazyRoute
  '/_authed/_dashboard/pipeline/': typeof AuthedDashboardPipelineIndexRoute
  '/_authed/_dashboard/player/': typeof AuthedDashboardPlayerIndexRoute
  '/_authed/_dashboard/sessions/': typeof AuthedDashboardSessionsIndexRoute
  '/_authed/_dashboard/notifications/': typeof AuthedDashboardNotificationsIndexLazyRoute
  '/_authed/_dashboard/streamers/': typeof AuthedDashboardStreamersIndexLazyRoute
  '/_authed/_dashboard/config/engines/$engineId': typeof AuthedDashboardConfigEnginesEngineIdLazyRoute
  '/_authed/_dashboard/config/engines/create': typeof AuthedDashboardConfigEnginesCreateLazyRoute
  '/_authed/_dashboard/config/platforms/$platformId': typeof AuthedDashboardConfigPlatformsPlatformIdLazyRoute
  '/_authed/_dashboard/config/templates/$templateId': typeof AuthedDashboardConfigTemplatesTemplateIdLazyRoute
  '/_authed/_dashboard/config/templates/create': typeof AuthedDashboardConfigTemplatesCreateLazyRoute
  '/_authed/_dashboard/pipeline/executions/$pipelineId': typeof AuthedDashboardPipelineExecutionsPipelineIdLazyRoute
  '/_authed/_dashboard/pipeline/jobs/$jobId': typeof AuthedDashboardPipelineJobsJobIdLazyRoute
  '/_authed/_dashboard/pipeline/jobs/new': typeof AuthedDashboardPipelineJobsNewLazyRoute
  '/_authed/_dashboard/pipeline/presets/$presetId': typeof AuthedDashboardPipelinePresetsPresetIdLazyRoute
  '/_authed/_dashboard/pipeline/presets/create': typeof AuthedDashboardPipelinePresetsCreateLazyRoute
  '/_authed/_dashboard/pipeline/workflows/$workflowId': typeof AuthedDashboardPipelineWorkflowsWorkflowIdLazyRoute
  '/_authed/_dashboard/pipeline/workflows/create': typeof AuthedDashboardPipelineWorkflowsCreateLazyRoute
  '/_authed/_dashboard/streamers/$id/edit': typeof AuthedDashboardStreamersIdEditLazyRoute
  '/_authed/_dashboard/pipeline/jobs/': typeof AuthedDashboardPipelineJobsIndexRoute
  '/_authed/_dashboard/config/engines/': typeof AuthedDashboardConfigEnginesIndexLazyRoute
  '/_authed/_dashboard/config/platforms/': typeof AuthedDashboardConfigPlatformsIndexLazyRoute
  '/_authed/_dashboard/config/templates/': typeof AuthedDashboardConfigTemplatesIndexLazyRoute
  '/_authed/_dashboard/pipeline/presets/': typeof AuthedDashboardPipelinePresetsIndexLazyRoute
  '/_authed/_dashboard/pipeline/workflows/': typeof AuthedDashboardPipelineWorkflowsIndexLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logout'
    | '/stream-proxy'
    | '/login'
    | '/change-password'
    | '/config'
    | '/dashboard'
    | '/config/backup'
    | '/config/global'
    | '/config/language'
    | '/config/logging'
    | '/config/theme'
    | '/notifications/events'
    | '/pipeline/outputs'
    | '/sessions/$sessionId'
    | '/streamers/new'
    | '/system/health'
    | '/pipeline/'
    | '/player/'
    | '/sessions/'
    | '/notifications/'
    | '/streamers/'
    | '/config/engines/$engineId'
    | '/config/engines/create'
    | '/config/platforms/$platformId'
    | '/config/templates/$templateId'
    | '/config/templates/create'
    | '/pipeline/executions/$pipelineId'
    | '/pipeline/jobs/$jobId'
    | '/pipeline/jobs/new'
    | '/pipeline/presets/$presetId'
    | '/pipeline/presets/create'
    | '/pipeline/workflows/$workflowId'
    | '/pipeline/workflows/create'
    | '/streamers/$id/edit'
    | '/pipeline/jobs/'
    | '/config/engines/'
    | '/config/platforms/'
    | '/config/templates/'
    | '/pipeline/presets/'
    | '/pipeline/workflows/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/stream-proxy'
    | '/login'
    | '/change-password'
    | '/config'
    | '/dashboard'
    | '/config/backup'
    | '/config/global'
    | '/config/language'
    | '/config/logging'
    | '/config/theme'
    | '/notifications/events'
    | '/pipeline/outputs'
    | '/sessions/$sessionId'
    | '/streamers/new'
    | '/system/health'
    | '/pipeline'
    | '/player'
    | '/sessions'
    | '/notifications'
    | '/streamers'
    | '/config/engines/$engineId'
    | '/config/engines/create'
    | '/config/platforms/$platformId'
    | '/config/templates/$templateId'
    | '/config/templates/create'
    | '/pipeline/executions/$pipelineId'
    | '/pipeline/jobs/$jobId'
    | '/pipeline/jobs/new'
    | '/pipeline/presets/$presetId'
    | '/pipeline/presets/create'
    | '/pipeline/workflows/$workflowId'
    | '/pipeline/workflows/create'
    | '/streamers/$id/edit'
    | '/pipeline/jobs'
    | '/config/engines'
    | '/config/platforms'
    | '/config/templates'
    | '/pipeline/presets'
    | '/pipeline/workflows'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_public'
    | '/logout'
    | '/stream-proxy'
    | '/_authed/_dashboard'
    | '/_public/login'
    | '/_authed/change-password'
    | '/_authed/_dashboard/config'
    | '/_authed/_dashboard/dashboard'
    | '/_authed/_dashboard/config/backup'
    | '/_authed/_dashboard/config/global'
    | '/_authed/_dashboard/config/language'
    | '/_authed/_dashboard/config/logging'
    | '/_authed/_dashboard/config/theme'
    | '/_authed/_dashboard/notifications/events'
    | '/_authed/_dashboard/pipeline/outputs'
    | '/_authed/_dashboard/sessions/$sessionId'
    | '/_authed/_dashboard/streamers/new'
    | '/_authed/_dashboard/system/health'
    | '/_authed/_dashboard/pipeline/'
    | '/_authed/_dashboard/player/'
    | '/_authed/_dashboard/sessions/'
    | '/_authed/_dashboard/notifications/'
    | '/_authed/_dashboard/streamers/'
    | '/_authed/_dashboard/config/engines/$engineId'
    | '/_authed/_dashboard/config/engines/create'
    | '/_authed/_dashboard/config/platforms/$platformId'
    | '/_authed/_dashboard/config/templates/$templateId'
    | '/_authed/_dashboard/config/templates/create'
    | '/_authed/_dashboard/pipeline/executions/$pipelineId'
    | '/_authed/_dashboard/pipeline/jobs/$jobId'
    | '/_authed/_dashboard/pipeline/jobs/new'
    | '/_authed/_dashboard/pipeline/presets/$presetId'
    | '/_authed/_dashboard/pipeline/presets/create'
    | '/_authed/_dashboard/pipeline/workflows/$workflowId'
    | '/_authed/_dashboard/pipeline/workflows/create'
    | '/_authed/_dashboard/streamers/$id/edit'
    | '/_authed/_dashboard/pipeline/jobs/'
    | '/_authed/_dashboard/config/engines/'
    | '/_authed/_dashboard/config/platforms/'
    | '/_authed/_dashboard/config/templates/'
    | '/_authed/_dashboard/pipeline/presets/'
    | '/_authed/_dashboard/pipeline/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  LogoutRoute: typeof LogoutRoute
  StreamProxyRoute: typeof StreamProxyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stream-proxy': {
      id: '/stream-proxy'
      path: '/stream-proxy'
      fullPath: '/stream-proxy'
      preLoaderRoute: typeof StreamProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/change-password': {
      id: '/_authed/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthedChangePasswordLazyRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authed/_dashboard': {
      id: '/_authed/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_dashboard/dashboard': {
      id: '/_authed/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardDashboardLazyRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/config': {
      id: '/_authed/_dashboard/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AuthedDashboardConfigRouteRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/streamers/': {
      id: '/_authed/_dashboard/streamers/'
      path: '/streamers'
      fullPath: '/streamers/'
      preLoaderRoute: typeof AuthedDashboardStreamersIndexLazyRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/notifications/': {
      id: '/_authed/_dashboard/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthedDashboardNotificationsIndexLazyRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/sessions/': {
      id: '/_authed/_dashboard/sessions/'
      path: '/sessions'
      fullPath: '/sessions/'
      preLoaderRoute: typeof AuthedDashboardSessionsIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/player/': {
      id: '/_authed/_dashboard/player/'
      path: '/player'
      fullPath: '/player/'
      preLoaderRoute: typeof AuthedDashboardPlayerIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/pipeline/': {
      id: '/_authed/_dashboard/pipeline/'
      path: '/pipeline'
      fullPath: '/pipeline/'
      preLoaderRoute: typeof AuthedDashboardPipelineIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/system/health': {
      id: '/_authed/_dashboard/system/health'
      path: '/system/health'
      fullPath: '/system/health'
      preLoaderRoute: typeof AuthedDashboardSystemHealthLazyRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/streamers/new': {
      id: '/_authed/_dashboard/streamers/new'
      path: '/streamers/new'
      fullPath: '/streamers/new'
      preLoaderRoute: typeof AuthedDashboardStreamersNewLazyRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/sessions/$sessionId': {
      id: '/_authed/_dashboard/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AuthedDashboardSessionsSessionIdLazyRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/pipeline/outputs': {
      id: '/_authed/_dashboard/pipeline/outputs'
      path: '/pipeline/outputs'
      fullPath: '/pipeline/outputs'
      preLoaderRoute: typeof AuthedDashboardPipelineOutputsLazyRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/notifications/events': {
      id: '/_authed/_dashboard/notifications/events'
      path: '/notifications/events'
      fullPath: '/notifications/events'
      preLoaderRoute: typeof AuthedDashboardNotificationsEventsLazyRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/config/theme': {
      id: '/_authed/_dashboard/config/theme'
      path: '/theme'
      fullPath: '/config/theme'
      preLoaderRoute: typeof AuthedDashboardConfigThemeLazyRouteImport
      parentRoute: typeof AuthedDashboardConfigRouteRoute
    }
    '/_authed/_dashboard/config/logging': {
      id: '/_authed/_dashboard/config/logging'
      path: '/logging'
      fullPath: '/config/logging'
      preLoaderRoute: typeof AuthedDashboardConfigLoggingLazyRouteImport
      parentRoute: typeof AuthedDashboardConfigRouteRoute
    }
    '/_authed/_dashboard/config/language': {
      id: '/_authed/_dashboard/config/language'
      path: '/language'
      fullPath: '/config/language'
      preLoaderRoute: typeof AuthedDashboardConfigLanguageLazyRouteImport
      parentRoute: typeof AuthedDashboardConfigRouteRoute
    }
    '/_authed/_dashboard/config/global': {
      id: '/_authed/_dashboard/config/global'
      path: '/global'
      fullPath: '/config/global'
      preLoaderRoute: typeof AuthedDashboardConfigGlobalLazyRouteImport
      parentRoute: typeof AuthedDashboardConfigRouteRoute
    }
    '/_authed/_dashboard/config/backup': {
      id: '/_authed/_dashboard/config/backup'
      path: '/backup'
      fullPath: '/config/backup'
      preLoaderRoute: typeof AuthedDashboardConfigBackupLazyRouteImport
      parentRoute: typeof AuthedDashboardConfigRouteRoute
    }
    '/_authed/_dashboard/pipeline/workflows/': {
      id: '/_authed/_dashboard/pipeline/workflows/'
      path: '/pipeline/workflows'
      fullPath: '/pipeline/workflows/'
      preLoaderRoute: typeof AuthedDashboardPipelineWorkflowsIndexLazyRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/pipeline/presets/': {
      id: '/_authed/_dashboard/pipeline/presets/'
      path: '/pipeline/presets'
      fullPath: '/pipeline/presets/'
      preLoaderRoute: typeof AuthedDashboardPipelinePresetsIndexLazyRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/config/templates/': {
      id: '/_authed/_dashboard/config/templates/'
      path: '/templates'
      fullPath: '/config/templates/'
      preLoaderRoute: typeof AuthedDashboardConfigTemplatesIndexLazyRouteImport
      parentRoute: typeof AuthedDashboardConfigRouteRoute
    }
    '/_authed/_dashboard/config/platforms/': {
      id: '/_authed/_dashboard/config/platforms/'
      path: '/platforms'
      fullPath: '/config/platforms/'
      preLoaderRoute: typeof AuthedDashboardConfigPlatformsIndexLazyRouteImport
      parentRoute: typeof AuthedDashboardConfigRouteRoute
    }
    '/_authed/_dashboard/config/engines/': {
      id: '/_authed/_dashboard/config/engines/'
      path: '/engines'
      fullPath: '/config/engines/'
      preLoaderRoute: typeof AuthedDashboardConfigEnginesIndexLazyRouteImport
      parentRoute: typeof AuthedDashboardConfigRouteRoute
    }
    '/_authed/_dashboard/pipeline/jobs/': {
      id: '/_authed/_dashboard/pipeline/jobs/'
      path: '/pipeline/jobs'
      fullPath: '/pipeline/jobs/'
      preLoaderRoute: typeof AuthedDashboardPipelineJobsIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/streamers/$id/edit': {
      id: '/_authed/_dashboard/streamers/$id/edit'
      path: '/streamers/$id/edit'
      fullPath: '/streamers/$id/edit'
      preLoaderRoute: typeof AuthedDashboardStreamersIdEditLazyRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/pipeline/workflows/create': {
      id: '/_authed/_dashboard/pipeline/workflows/create'
      path: '/pipeline/workflows/create'
      fullPath: '/pipeline/workflows/create'
      preLoaderRoute: typeof AuthedDashboardPipelineWorkflowsCreateLazyRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/pipeline/workflows/$workflowId': {
      id: '/_authed/_dashboard/pipeline/workflows/$workflowId'
      path: '/pipeline/workflows/$workflowId'
      fullPath: '/pipeline/workflows/$workflowId'
      preLoaderRoute: typeof AuthedDashboardPipelineWorkflowsWorkflowIdLazyRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/pipeline/presets/create': {
      id: '/_authed/_dashboard/pipeline/presets/create'
      path: '/pipeline/presets/create'
      fullPath: '/pipeline/presets/create'
      preLoaderRoute: typeof AuthedDashboardPipelinePresetsCreateLazyRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/pipeline/presets/$presetId': {
      id: '/_authed/_dashboard/pipeline/presets/$presetId'
      path: '/pipeline/presets/$presetId'
      fullPath: '/pipeline/presets/$presetId'
      preLoaderRoute: typeof AuthedDashboardPipelinePresetsPresetIdLazyRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/pipeline/jobs/new': {
      id: '/_authed/_dashboard/pipeline/jobs/new'
      path: '/pipeline/jobs/new'
      fullPath: '/pipeline/jobs/new'
      preLoaderRoute: typeof AuthedDashboardPipelineJobsNewLazyRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/pipeline/jobs/$jobId': {
      id: '/_authed/_dashboard/pipeline/jobs/$jobId'
      path: '/pipeline/jobs/$jobId'
      fullPath: '/pipeline/jobs/$jobId'
      preLoaderRoute: typeof AuthedDashboardPipelineJobsJobIdLazyRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/pipeline/executions/$pipelineId': {
      id: '/_authed/_dashboard/pipeline/executions/$pipelineId'
      path: '/pipeline/executions/$pipelineId'
      fullPath: '/pipeline/executions/$pipelineId'
      preLoaderRoute: typeof AuthedDashboardPipelineExecutionsPipelineIdLazyRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/config/templates/create': {
      id: '/_authed/_dashboard/config/templates/create'
      path: '/templates/create'
      fullPath: '/config/templates/create'
      preLoaderRoute: typeof AuthedDashboardConfigTemplatesCreateLazyRouteImport
      parentRoute: typeof AuthedDashboardConfigRouteRoute
    }
    '/_authed/_dashboard/config/templates/$templateId': {
      id: '/_authed/_dashboard/config/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/config/templates/$templateId'
      preLoaderRoute: typeof AuthedDashboardConfigTemplatesTemplateIdLazyRouteImport
      parentRoute: typeof AuthedDashboardConfigRouteRoute
    }
    '/_authed/_dashboard/config/platforms/$platformId': {
      id: '/_authed/_dashboard/config/platforms/$platformId'
      path: '/platforms/$platformId'
      fullPath: '/config/platforms/$platformId'
      preLoaderRoute: typeof AuthedDashboardConfigPlatformsPlatformIdLazyRouteImport
      parentRoute: typeof AuthedDashboardConfigRouteRoute
    }
    '/_authed/_dashboard/config/engines/create': {
      id: '/_authed/_dashboard/config/engines/create'
      path: '/engines/create'
      fullPath: '/config/engines/create'
      preLoaderRoute: typeof AuthedDashboardConfigEnginesCreateLazyRouteImport
      parentRoute: typeof AuthedDashboardConfigRouteRoute
    }
    '/_authed/_dashboard/config/engines/$engineId': {
      id: '/_authed/_dashboard/config/engines/$engineId'
      path: '/engines/$engineId'
      fullPath: '/config/engines/$engineId'
      preLoaderRoute: typeof AuthedDashboardConfigEnginesEngineIdLazyRouteImport
      parentRoute: typeof AuthedDashboardConfigRouteRoute
    }
  }
}

interface AuthedDashboardConfigRouteRouteChildren {
  AuthedDashboardConfigBackupLazyRoute: typeof AuthedDashboardConfigBackupLazyRoute
  AuthedDashboardConfigGlobalLazyRoute: typeof AuthedDashboardConfigGlobalLazyRoute
  AuthedDashboardConfigLanguageLazyRoute: typeof AuthedDashboardConfigLanguageLazyRoute
  AuthedDashboardConfigLoggingLazyRoute: typeof AuthedDashboardConfigLoggingLazyRoute
  AuthedDashboardConfigThemeLazyRoute: typeof AuthedDashboardConfigThemeLazyRoute
  AuthedDashboardConfigEnginesEngineIdLazyRoute: typeof AuthedDashboardConfigEnginesEngineIdLazyRoute
  AuthedDashboardConfigEnginesCreateLazyRoute: typeof AuthedDashboardConfigEnginesCreateLazyRoute
  AuthedDashboardConfigPlatformsPlatformIdLazyRoute: typeof AuthedDashboardConfigPlatformsPlatformIdLazyRoute
  AuthedDashboardConfigTemplatesTemplateIdLazyRoute: typeof AuthedDashboardConfigTemplatesTemplateIdLazyRoute
  AuthedDashboardConfigTemplatesCreateLazyRoute: typeof AuthedDashboardConfigTemplatesCreateLazyRoute
  AuthedDashboardConfigEnginesIndexLazyRoute: typeof AuthedDashboardConfigEnginesIndexLazyRoute
  AuthedDashboardConfigPlatformsIndexLazyRoute: typeof AuthedDashboardConfigPlatformsIndexLazyRoute
  AuthedDashboardConfigTemplatesIndexLazyRoute: typeof AuthedDashboardConfigTemplatesIndexLazyRoute
}

const AuthedDashboardConfigRouteRouteChildren: AuthedDashboardConfigRouteRouteChildren =
  {
    AuthedDashboardConfigBackupLazyRoute: AuthedDashboardConfigBackupLazyRoute,
    AuthedDashboardConfigGlobalLazyRoute: AuthedDashboardConfigGlobalLazyRoute,
    AuthedDashboardConfigLanguageLazyRoute:
      AuthedDashboardConfigLanguageLazyRoute,
    AuthedDashboardConfigLoggingLazyRoute:
      AuthedDashboardConfigLoggingLazyRoute,
    AuthedDashboardConfigThemeLazyRoute: AuthedDashboardConfigThemeLazyRoute,
    AuthedDashboardConfigEnginesEngineIdLazyRoute:
      AuthedDashboardConfigEnginesEngineIdLazyRoute,
    AuthedDashboardConfigEnginesCreateLazyRoute:
      AuthedDashboardConfigEnginesCreateLazyRoute,
    AuthedDashboardConfigPlatformsPlatformIdLazyRoute:
      AuthedDashboardConfigPlatformsPlatformIdLazyRoute,
    AuthedDashboardConfigTemplatesTemplateIdLazyRoute:
      AuthedDashboardConfigTemplatesTemplateIdLazyRoute,
    AuthedDashboardConfigTemplatesCreateLazyRoute:
      AuthedDashboardConfigTemplatesCreateLazyRoute,
    AuthedDashboardConfigEnginesIndexLazyRoute:
      AuthedDashboardConfigEnginesIndexLazyRoute,
    AuthedDashboardConfigPlatformsIndexLazyRoute:
      AuthedDashboardConfigPlatformsIndexLazyRoute,
    AuthedDashboardConfigTemplatesIndexLazyRoute:
      AuthedDashboardConfigTemplatesIndexLazyRoute,
  }

const AuthedDashboardConfigRouteRouteWithChildren =
  AuthedDashboardConfigRouteRoute._addFileChildren(
    AuthedDashboardConfigRouteRouteChildren,
  )

interface AuthedDashboardRouteChildren {
  AuthedDashboardConfigRouteRoute: typeof AuthedDashboardConfigRouteRouteWithChildren
  AuthedDashboardDashboardLazyRoute: typeof AuthedDashboardDashboardLazyRoute
  AuthedDashboardNotificationsEventsLazyRoute: typeof AuthedDashboardNotificationsEventsLazyRoute
  AuthedDashboardPipelineOutputsLazyRoute: typeof AuthedDashboardPipelineOutputsLazyRoute
  AuthedDashboardSessionsSessionIdLazyRoute: typeof AuthedDashboardSessionsSessionIdLazyRoute
  AuthedDashboardStreamersNewLazyRoute: typeof AuthedDashboardStreamersNewLazyRoute
  AuthedDashboardSystemHealthLazyRoute: typeof AuthedDashboardSystemHealthLazyRoute
  AuthedDashboardPipelineIndexRoute: typeof AuthedDashboardPipelineIndexRoute
  AuthedDashboardPlayerIndexRoute: typeof AuthedDashboardPlayerIndexRoute
  AuthedDashboardSessionsIndexRoute: typeof AuthedDashboardSessionsIndexRoute
  AuthedDashboardNotificationsIndexLazyRoute: typeof AuthedDashboardNotificationsIndexLazyRoute
  AuthedDashboardStreamersIndexLazyRoute: typeof AuthedDashboardStreamersIndexLazyRoute
  AuthedDashboardPipelineExecutionsPipelineIdLazyRoute: typeof AuthedDashboardPipelineExecutionsPipelineIdLazyRoute
  AuthedDashboardPipelineJobsJobIdLazyRoute: typeof AuthedDashboardPipelineJobsJobIdLazyRoute
  AuthedDashboardPipelineJobsNewLazyRoute: typeof AuthedDashboardPipelineJobsNewLazyRoute
  AuthedDashboardPipelinePresetsPresetIdLazyRoute: typeof AuthedDashboardPipelinePresetsPresetIdLazyRoute
  AuthedDashboardPipelinePresetsCreateLazyRoute: typeof AuthedDashboardPipelinePresetsCreateLazyRoute
  AuthedDashboardPipelineWorkflowsWorkflowIdLazyRoute: typeof AuthedDashboardPipelineWorkflowsWorkflowIdLazyRoute
  AuthedDashboardPipelineWorkflowsCreateLazyRoute: typeof AuthedDashboardPipelineWorkflowsCreateLazyRoute
  AuthedDashboardStreamersIdEditLazyRoute: typeof AuthedDashboardStreamersIdEditLazyRoute
  AuthedDashboardPipelineJobsIndexRoute: typeof AuthedDashboardPipelineJobsIndexRoute
  AuthedDashboardPipelinePresetsIndexLazyRoute: typeof AuthedDashboardPipelinePresetsIndexLazyRoute
  AuthedDashboardPipelineWorkflowsIndexLazyRoute: typeof AuthedDashboardPipelineWorkflowsIndexLazyRoute
}

const AuthedDashboardRouteChildren: AuthedDashboardRouteChildren = {
  AuthedDashboardConfigRouteRoute: AuthedDashboardConfigRouteRouteWithChildren,
  AuthedDashboardDashboardLazyRoute: AuthedDashboardDashboardLazyRoute,
  AuthedDashboardNotificationsEventsLazyRoute:
    AuthedDashboardNotificationsEventsLazyRoute,
  AuthedDashboardPipelineOutputsLazyRoute:
    AuthedDashboardPipelineOutputsLazyRoute,
  AuthedDashboardSessionsSessionIdLazyRoute:
    AuthedDashboardSessionsSessionIdLazyRoute,
  AuthedDashboardStreamersNewLazyRoute: AuthedDashboardStreamersNewLazyRoute,
  AuthedDashboardSystemHealthLazyRoute: AuthedDashboardSystemHealthLazyRoute,
  AuthedDashboardPipelineIndexRoute: AuthedDashboardPipelineIndexRoute,
  AuthedDashboardPlayerIndexRoute: AuthedDashboardPlayerIndexRoute,
  AuthedDashboardSessionsIndexRoute: AuthedDashboardSessionsIndexRoute,
  AuthedDashboardNotificationsIndexLazyRoute:
    AuthedDashboardNotificationsIndexLazyRoute,
  AuthedDashboardStreamersIndexLazyRoute:
    AuthedDashboardStreamersIndexLazyRoute,
  AuthedDashboardPipelineExecutionsPipelineIdLazyRoute:
    AuthedDashboardPipelineExecutionsPipelineIdLazyRoute,
  AuthedDashboardPipelineJobsJobIdLazyRoute:
    AuthedDashboardPipelineJobsJobIdLazyRoute,
  AuthedDashboardPipelineJobsNewLazyRoute:
    AuthedDashboardPipelineJobsNewLazyRoute,
  AuthedDashboardPipelinePresetsPresetIdLazyRoute:
    AuthedDashboardPipelinePresetsPresetIdLazyRoute,
  AuthedDashboardPipelinePresetsCreateLazyRoute:
    AuthedDashboardPipelinePresetsCreateLazyRoute,
  AuthedDashboardPipelineWorkflowsWorkflowIdLazyRoute:
    AuthedDashboardPipelineWorkflowsWorkflowIdLazyRoute,
  AuthedDashboardPipelineWorkflowsCreateLazyRoute:
    AuthedDashboardPipelineWorkflowsCreateLazyRoute,
  AuthedDashboardStreamersIdEditLazyRoute:
    AuthedDashboardStreamersIdEditLazyRoute,
  AuthedDashboardPipelineJobsIndexRoute: AuthedDashboardPipelineJobsIndexRoute,
  AuthedDashboardPipelinePresetsIndexLazyRoute:
    AuthedDashboardPipelinePresetsIndexLazyRoute,
  AuthedDashboardPipelineWorkflowsIndexLazyRoute:
    AuthedDashboardPipelineWorkflowsIndexLazyRoute,
}

const AuthedDashboardRouteWithChildren = AuthedDashboardRoute._addFileChildren(
  AuthedDashboardRouteChildren,
)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRouteWithChildren
  AuthedChangePasswordLazyRoute: typeof AuthedChangePasswordLazyRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRouteWithChildren,
  AuthedChangePasswordLazyRoute: AuthedChangePasswordLazyRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  LogoutRoute: LogoutRoute,
  StreamProxyRoute: StreamProxyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
