/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StreamProxyRouteImport } from './routes/stream-proxy'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthedChangePasswordRouteImport } from './routes/_authed/change-password'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/_dashboard'
import { Route as AuthedDashboardDashboardRouteImport } from './routes/_authed/_dashboard/dashboard'
import { Route as AuthedDashboardConfigRouteRouteImport } from './routes/_authed/_dashboard/config/route'
import { Route as AuthedDashboardStreamersIndexRouteImport } from './routes/_authed/_dashboard/streamers/index'
import { Route as AuthedDashboardSessionsIndexRouteImport } from './routes/_authed/_dashboard/sessions/index'
import { Route as AuthedDashboardPlayerIndexRouteImport } from './routes/_authed/_dashboard/player/index'
import { Route as AuthedDashboardPipelineIndexRouteImport } from './routes/_authed/_dashboard/pipeline/index'
import { Route as AuthedDashboardNotificationsIndexRouteImport } from './routes/_authed/_dashboard/notifications/index'
import { Route as AuthedDashboardSystemHealthRouteImport } from './routes/_authed/_dashboard/system/health'
import { Route as AuthedDashboardStreamersNewRouteImport } from './routes/_authed/_dashboard/streamers/new'
import { Route as AuthedDashboardSessionsSessionIdRouteImport } from './routes/_authed/_dashboard/sessions/$sessionId'
import { Route as AuthedDashboardPipelineOutputsRouteImport } from './routes/_authed/_dashboard/pipeline/outputs'
import { Route as AuthedDashboardNotificationsEventsRouteImport } from './routes/_authed/_dashboard/notifications/events'
import { Route as AuthedDashboardConfigThemeRouteImport } from './routes/_authed/_dashboard/config/theme'
import { Route as AuthedDashboardConfigLoggingRouteImport } from './routes/_authed/_dashboard/config/logging'
import { Route as AuthedDashboardConfigLanguageRouteImport } from './routes/_authed/_dashboard/config/language'
import { Route as AuthedDashboardConfigGlobalRouteImport } from './routes/_authed/_dashboard/config/global'
import { Route as AuthedDashboardConfigBackupRouteImport } from './routes/_authed/_dashboard/config/backup'
import { Route as AuthedDashboardPipelineWorkflowsIndexRouteImport } from './routes/_authed/_dashboard/pipeline/workflows/index'
import { Route as AuthedDashboardPipelinePresetsIndexRouteImport } from './routes/_authed/_dashboard/pipeline/presets/index'
import { Route as AuthedDashboardPipelineJobsIndexRouteImport } from './routes/_authed/_dashboard/pipeline/jobs/index'
import { Route as AuthedDashboardConfigTemplatesIndexRouteImport } from './routes/_authed/_dashboard/config/templates/index'
import { Route as AuthedDashboardConfigPlatformsIndexRouteImport } from './routes/_authed/_dashboard/config/platforms/index'
import { Route as AuthedDashboardConfigEnginesIndexRouteImport } from './routes/_authed/_dashboard/config/engines/index'
import { Route as AuthedDashboardStreamersIdEditRouteImport } from './routes/_authed/_dashboard/streamers/$id.edit'
import { Route as AuthedDashboardPipelineWorkflowsCreateRouteImport } from './routes/_authed/_dashboard/pipeline/workflows/create'
import { Route as AuthedDashboardPipelineWorkflowsWorkflowIdRouteImport } from './routes/_authed/_dashboard/pipeline/workflows/$workflowId'
import { Route as AuthedDashboardPipelinePresetsCreateRouteImport } from './routes/_authed/_dashboard/pipeline/presets/create'
import { Route as AuthedDashboardPipelinePresetsPresetIdRouteImport } from './routes/_authed/_dashboard/pipeline/presets/$presetId'
import { Route as AuthedDashboardPipelineJobsNewRouteImport } from './routes/_authed/_dashboard/pipeline/jobs/new'
import { Route as AuthedDashboardPipelineJobsJobIdRouteImport } from './routes/_authed/_dashboard/pipeline/jobs/$jobId'
import { Route as AuthedDashboardPipelineExecutionsPipelineIdRouteImport } from './routes/_authed/_dashboard/pipeline/executions.$pipelineId'
import { Route as AuthedDashboardConfigTemplatesCreateRouteImport } from './routes/_authed/_dashboard/config/templates/create'
import { Route as AuthedDashboardConfigTemplatesTemplateIdRouteImport } from './routes/_authed/_dashboard/config/templates/$templateId'
import { Route as AuthedDashboardConfigPlatformsPlatformIdRouteImport } from './routes/_authed/_dashboard/config/platforms/$platformId'
import { Route as AuthedDashboardConfigEnginesCreateRouteImport } from './routes/_authed/_dashboard/config/engines/create'
import { Route as AuthedDashboardConfigEnginesEngineIdRouteImport } from './routes/_authed/_dashboard/config/engines/$engineId'

const StreamProxyRoute = StreamProxyRouteImport.update({
  id: '/stream-proxy',
  path: '/stream-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const AuthedChangePasswordRoute = AuthedChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardDashboardRoute =
  AuthedDashboardDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardConfigRouteRoute =
  AuthedDashboardConfigRouteRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardStreamersIndexRoute =
  AuthedDashboardStreamersIndexRouteImport.update({
    id: '/streamers/',
    path: '/streamers/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardSessionsIndexRoute =
  AuthedDashboardSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardPlayerIndexRoute =
  AuthedDashboardPlayerIndexRouteImport.update({
    id: '/player/',
    path: '/player/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardPipelineIndexRoute =
  AuthedDashboardPipelineIndexRouteImport.update({
    id: '/pipeline/',
    path: '/pipeline/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardNotificationsIndexRoute =
  AuthedDashboardNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardSystemHealthRoute =
  AuthedDashboardSystemHealthRouteImport.update({
    id: '/system/health',
    path: '/system/health',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardStreamersNewRoute =
  AuthedDashboardStreamersNewRouteImport.update({
    id: '/streamers/new',
    path: '/streamers/new',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardSessionsSessionIdRoute =
  AuthedDashboardSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardPipelineOutputsRoute =
  AuthedDashboardPipelineOutputsRouteImport.update({
    id: '/pipeline/outputs',
    path: '/pipeline/outputs',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardNotificationsEventsRoute =
  AuthedDashboardNotificationsEventsRouteImport.update({
    id: '/notifications/events',
    path: '/notifications/events',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardConfigThemeRoute =
  AuthedDashboardConfigThemeRouteImport.update({
    id: '/theme',
    path: '/theme',
    getParentRoute: () => AuthedDashboardConfigRouteRoute,
  } as any)
const AuthedDashboardConfigLoggingRoute =
  AuthedDashboardConfigLoggingRouteImport.update({
    id: '/logging',
    path: '/logging',
    getParentRoute: () => AuthedDashboardConfigRouteRoute,
  } as any)
const AuthedDashboardConfigLanguageRoute =
  AuthedDashboardConfigLanguageRouteImport.update({
    id: '/language',
    path: '/language',
    getParentRoute: () => AuthedDashboardConfigRouteRoute,
  } as any)
const AuthedDashboardConfigGlobalRoute =
  AuthedDashboardConfigGlobalRouteImport.update({
    id: '/global',
    path: '/global',
    getParentRoute: () => AuthedDashboardConfigRouteRoute,
  } as any)
const AuthedDashboardConfigBackupRoute =
  AuthedDashboardConfigBackupRouteImport.update({
    id: '/backup',
    path: '/backup',
    getParentRoute: () => AuthedDashboardConfigRouteRoute,
  } as any)
const AuthedDashboardPipelineWorkflowsIndexRoute =
  AuthedDashboardPipelineWorkflowsIndexRouteImport.update({
    id: '/pipeline/workflows/',
    path: '/pipeline/workflows/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardPipelinePresetsIndexRoute =
  AuthedDashboardPipelinePresetsIndexRouteImport.update({
    id: '/pipeline/presets/',
    path: '/pipeline/presets/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardPipelineJobsIndexRoute =
  AuthedDashboardPipelineJobsIndexRouteImport.update({
    id: '/pipeline/jobs/',
    path: '/pipeline/jobs/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardConfigTemplatesIndexRoute =
  AuthedDashboardConfigTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthedDashboardConfigRouteRoute,
  } as any)
const AuthedDashboardConfigPlatformsIndexRoute =
  AuthedDashboardConfigPlatformsIndexRouteImport.update({
    id: '/platforms/',
    path: '/platforms/',
    getParentRoute: () => AuthedDashboardConfigRouteRoute,
  } as any)
const AuthedDashboardConfigEnginesIndexRoute =
  AuthedDashboardConfigEnginesIndexRouteImport.update({
    id: '/engines/',
    path: '/engines/',
    getParentRoute: () => AuthedDashboardConfigRouteRoute,
  } as any)
const AuthedDashboardStreamersIdEditRoute =
  AuthedDashboardStreamersIdEditRouteImport.update({
    id: '/streamers/$id/edit',
    path: '/streamers/$id/edit',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardPipelineWorkflowsCreateRoute =
  AuthedDashboardPipelineWorkflowsCreateRouteImport.update({
    id: '/pipeline/workflows/create',
    path: '/pipeline/workflows/create',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardPipelineWorkflowsWorkflowIdRoute =
  AuthedDashboardPipelineWorkflowsWorkflowIdRouteImport.update({
    id: '/pipeline/workflows/$workflowId',
    path: '/pipeline/workflows/$workflowId',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardPipelinePresetsCreateRoute =
  AuthedDashboardPipelinePresetsCreateRouteImport.update({
    id: '/pipeline/presets/create',
    path: '/pipeline/presets/create',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardPipelinePresetsPresetIdRoute =
  AuthedDashboardPipelinePresetsPresetIdRouteImport.update({
    id: '/pipeline/presets/$presetId',
    path: '/pipeline/presets/$presetId',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardPipelineJobsNewRoute =
  AuthedDashboardPipelineJobsNewRouteImport.update({
    id: '/pipeline/jobs/new',
    path: '/pipeline/jobs/new',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardPipelineJobsJobIdRoute =
  AuthedDashboardPipelineJobsJobIdRouteImport.update({
    id: '/pipeline/jobs/$jobId',
    path: '/pipeline/jobs/$jobId',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardPipelineExecutionsPipelineIdRoute =
  AuthedDashboardPipelineExecutionsPipelineIdRouteImport.update({
    id: '/pipeline/executions/$pipelineId',
    path: '/pipeline/executions/$pipelineId',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardConfigTemplatesCreateRoute =
  AuthedDashboardConfigTemplatesCreateRouteImport.update({
    id: '/templates/create',
    path: '/templates/create',
    getParentRoute: () => AuthedDashboardConfigRouteRoute,
  } as any)
const AuthedDashboardConfigTemplatesTemplateIdRoute =
  AuthedDashboardConfigTemplatesTemplateIdRouteImport.update({
    id: '/templates/$templateId',
    path: '/templates/$templateId',
    getParentRoute: () => AuthedDashboardConfigRouteRoute,
  } as any)
const AuthedDashboardConfigPlatformsPlatformIdRoute =
  AuthedDashboardConfigPlatformsPlatformIdRouteImport.update({
    id: '/platforms/$platformId',
    path: '/platforms/$platformId',
    getParentRoute: () => AuthedDashboardConfigRouteRoute,
  } as any)
const AuthedDashboardConfigEnginesCreateRoute =
  AuthedDashboardConfigEnginesCreateRouteImport.update({
    id: '/engines/create',
    path: '/engines/create',
    getParentRoute: () => AuthedDashboardConfigRouteRoute,
  } as any)
const AuthedDashboardConfigEnginesEngineIdRoute =
  AuthedDashboardConfigEnginesEngineIdRouteImport.update({
    id: '/engines/$engineId',
    path: '/engines/$engineId',
    getParentRoute: () => AuthedDashboardConfigRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/stream-proxy': typeof StreamProxyRoute
  '/change-password': typeof AuthedChangePasswordRoute
  '/login': typeof PublicLoginRoute
  '/config': typeof AuthedDashboardConfigRouteRouteWithChildren
  '/dashboard': typeof AuthedDashboardDashboardRoute
  '/config/backup': typeof AuthedDashboardConfigBackupRoute
  '/config/global': typeof AuthedDashboardConfigGlobalRoute
  '/config/language': typeof AuthedDashboardConfigLanguageRoute
  '/config/logging': typeof AuthedDashboardConfigLoggingRoute
  '/config/theme': typeof AuthedDashboardConfigThemeRoute
  '/notifications/events': typeof AuthedDashboardNotificationsEventsRoute
  '/pipeline/outputs': typeof AuthedDashboardPipelineOutputsRoute
  '/sessions/$sessionId': typeof AuthedDashboardSessionsSessionIdRoute
  '/streamers/new': typeof AuthedDashboardStreamersNewRoute
  '/system/health': typeof AuthedDashboardSystemHealthRoute
  '/notifications': typeof AuthedDashboardNotificationsIndexRoute
  '/pipeline': typeof AuthedDashboardPipelineIndexRoute
  '/player': typeof AuthedDashboardPlayerIndexRoute
  '/sessions': typeof AuthedDashboardSessionsIndexRoute
  '/streamers': typeof AuthedDashboardStreamersIndexRoute
  '/config/engines/$engineId': typeof AuthedDashboardConfigEnginesEngineIdRoute
  '/config/engines/create': typeof AuthedDashboardConfigEnginesCreateRoute
  '/config/platforms/$platformId': typeof AuthedDashboardConfigPlatformsPlatformIdRoute
  '/config/templates/$templateId': typeof AuthedDashboardConfigTemplatesTemplateIdRoute
  '/config/templates/create': typeof AuthedDashboardConfigTemplatesCreateRoute
  '/pipeline/executions/$pipelineId': typeof AuthedDashboardPipelineExecutionsPipelineIdRoute
  '/pipeline/jobs/$jobId': typeof AuthedDashboardPipelineJobsJobIdRoute
  '/pipeline/jobs/new': typeof AuthedDashboardPipelineJobsNewRoute
  '/pipeline/presets/$presetId': typeof AuthedDashboardPipelinePresetsPresetIdRoute
  '/pipeline/presets/create': typeof AuthedDashboardPipelinePresetsCreateRoute
  '/pipeline/workflows/$workflowId': typeof AuthedDashboardPipelineWorkflowsWorkflowIdRoute
  '/pipeline/workflows/create': typeof AuthedDashboardPipelineWorkflowsCreateRoute
  '/streamers/$id/edit': typeof AuthedDashboardStreamersIdEditRoute
  '/config/engines': typeof AuthedDashboardConfigEnginesIndexRoute
  '/config/platforms': typeof AuthedDashboardConfigPlatformsIndexRoute
  '/config/templates': typeof AuthedDashboardConfigTemplatesIndexRoute
  '/pipeline/jobs': typeof AuthedDashboardPipelineJobsIndexRoute
  '/pipeline/presets': typeof AuthedDashboardPipelinePresetsIndexRoute
  '/pipeline/workflows': typeof AuthedDashboardPipelineWorkflowsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/stream-proxy': typeof StreamProxyRoute
  '/change-password': typeof AuthedChangePasswordRoute
  '/login': typeof PublicLoginRoute
  '/config': typeof AuthedDashboardConfigRouteRouteWithChildren
  '/dashboard': typeof AuthedDashboardDashboardRoute
  '/config/backup': typeof AuthedDashboardConfigBackupRoute
  '/config/global': typeof AuthedDashboardConfigGlobalRoute
  '/config/language': typeof AuthedDashboardConfigLanguageRoute
  '/config/logging': typeof AuthedDashboardConfigLoggingRoute
  '/config/theme': typeof AuthedDashboardConfigThemeRoute
  '/notifications/events': typeof AuthedDashboardNotificationsEventsRoute
  '/pipeline/outputs': typeof AuthedDashboardPipelineOutputsRoute
  '/sessions/$sessionId': typeof AuthedDashboardSessionsSessionIdRoute
  '/streamers/new': typeof AuthedDashboardStreamersNewRoute
  '/system/health': typeof AuthedDashboardSystemHealthRoute
  '/notifications': typeof AuthedDashboardNotificationsIndexRoute
  '/pipeline': typeof AuthedDashboardPipelineIndexRoute
  '/player': typeof AuthedDashboardPlayerIndexRoute
  '/sessions': typeof AuthedDashboardSessionsIndexRoute
  '/streamers': typeof AuthedDashboardStreamersIndexRoute
  '/config/engines/$engineId': typeof AuthedDashboardConfigEnginesEngineIdRoute
  '/config/engines/create': typeof AuthedDashboardConfigEnginesCreateRoute
  '/config/platforms/$platformId': typeof AuthedDashboardConfigPlatformsPlatformIdRoute
  '/config/templates/$templateId': typeof AuthedDashboardConfigTemplatesTemplateIdRoute
  '/config/templates/create': typeof AuthedDashboardConfigTemplatesCreateRoute
  '/pipeline/executions/$pipelineId': typeof AuthedDashboardPipelineExecutionsPipelineIdRoute
  '/pipeline/jobs/$jobId': typeof AuthedDashboardPipelineJobsJobIdRoute
  '/pipeline/jobs/new': typeof AuthedDashboardPipelineJobsNewRoute
  '/pipeline/presets/$presetId': typeof AuthedDashboardPipelinePresetsPresetIdRoute
  '/pipeline/presets/create': typeof AuthedDashboardPipelinePresetsCreateRoute
  '/pipeline/workflows/$workflowId': typeof AuthedDashboardPipelineWorkflowsWorkflowIdRoute
  '/pipeline/workflows/create': typeof AuthedDashboardPipelineWorkflowsCreateRoute
  '/streamers/$id/edit': typeof AuthedDashboardStreamersIdEditRoute
  '/config/engines': typeof AuthedDashboardConfigEnginesIndexRoute
  '/config/platforms': typeof AuthedDashboardConfigPlatformsIndexRoute
  '/config/templates': typeof AuthedDashboardConfigTemplatesIndexRoute
  '/pipeline/jobs': typeof AuthedDashboardPipelineJobsIndexRoute
  '/pipeline/presets': typeof AuthedDashboardPipelinePresetsIndexRoute
  '/pipeline/workflows': typeof AuthedDashboardPipelineWorkflowsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/logout': typeof LogoutRoute
  '/stream-proxy': typeof StreamProxyRoute
  '/_authed/_dashboard': typeof AuthedDashboardRouteWithChildren
  '/_authed/change-password': typeof AuthedChangePasswordRoute
  '/_public/login': typeof PublicLoginRoute
  '/_authed/_dashboard/config': typeof AuthedDashboardConfigRouteRouteWithChildren
  '/_authed/_dashboard/dashboard': typeof AuthedDashboardDashboardRoute
  '/_authed/_dashboard/config/backup': typeof AuthedDashboardConfigBackupRoute
  '/_authed/_dashboard/config/global': typeof AuthedDashboardConfigGlobalRoute
  '/_authed/_dashboard/config/language': typeof AuthedDashboardConfigLanguageRoute
  '/_authed/_dashboard/config/logging': typeof AuthedDashboardConfigLoggingRoute
  '/_authed/_dashboard/config/theme': typeof AuthedDashboardConfigThemeRoute
  '/_authed/_dashboard/notifications/events': typeof AuthedDashboardNotificationsEventsRoute
  '/_authed/_dashboard/pipeline/outputs': typeof AuthedDashboardPipelineOutputsRoute
  '/_authed/_dashboard/sessions/$sessionId': typeof AuthedDashboardSessionsSessionIdRoute
  '/_authed/_dashboard/streamers/new': typeof AuthedDashboardStreamersNewRoute
  '/_authed/_dashboard/system/health': typeof AuthedDashboardSystemHealthRoute
  '/_authed/_dashboard/notifications/': typeof AuthedDashboardNotificationsIndexRoute
  '/_authed/_dashboard/pipeline/': typeof AuthedDashboardPipelineIndexRoute
  '/_authed/_dashboard/player/': typeof AuthedDashboardPlayerIndexRoute
  '/_authed/_dashboard/sessions/': typeof AuthedDashboardSessionsIndexRoute
  '/_authed/_dashboard/streamers/': typeof AuthedDashboardStreamersIndexRoute
  '/_authed/_dashboard/config/engines/$engineId': typeof AuthedDashboardConfigEnginesEngineIdRoute
  '/_authed/_dashboard/config/engines/create': typeof AuthedDashboardConfigEnginesCreateRoute
  '/_authed/_dashboard/config/platforms/$platformId': typeof AuthedDashboardConfigPlatformsPlatformIdRoute
  '/_authed/_dashboard/config/templates/$templateId': typeof AuthedDashboardConfigTemplatesTemplateIdRoute
  '/_authed/_dashboard/config/templates/create': typeof AuthedDashboardConfigTemplatesCreateRoute
  '/_authed/_dashboard/pipeline/executions/$pipelineId': typeof AuthedDashboardPipelineExecutionsPipelineIdRoute
  '/_authed/_dashboard/pipeline/jobs/$jobId': typeof AuthedDashboardPipelineJobsJobIdRoute
  '/_authed/_dashboard/pipeline/jobs/new': typeof AuthedDashboardPipelineJobsNewRoute
  '/_authed/_dashboard/pipeline/presets/$presetId': typeof AuthedDashboardPipelinePresetsPresetIdRoute
  '/_authed/_dashboard/pipeline/presets/create': typeof AuthedDashboardPipelinePresetsCreateRoute
  '/_authed/_dashboard/pipeline/workflows/$workflowId': typeof AuthedDashboardPipelineWorkflowsWorkflowIdRoute
  '/_authed/_dashboard/pipeline/workflows/create': typeof AuthedDashboardPipelineWorkflowsCreateRoute
  '/_authed/_dashboard/streamers/$id/edit': typeof AuthedDashboardStreamersIdEditRoute
  '/_authed/_dashboard/config/engines/': typeof AuthedDashboardConfigEnginesIndexRoute
  '/_authed/_dashboard/config/platforms/': typeof AuthedDashboardConfigPlatformsIndexRoute
  '/_authed/_dashboard/config/templates/': typeof AuthedDashboardConfigTemplatesIndexRoute
  '/_authed/_dashboard/pipeline/jobs/': typeof AuthedDashboardPipelineJobsIndexRoute
  '/_authed/_dashboard/pipeline/presets/': typeof AuthedDashboardPipelinePresetsIndexRoute
  '/_authed/_dashboard/pipeline/workflows/': typeof AuthedDashboardPipelineWorkflowsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logout'
    | '/stream-proxy'
    | '/change-password'
    | '/login'
    | '/config'
    | '/dashboard'
    | '/config/backup'
    | '/config/global'
    | '/config/language'
    | '/config/logging'
    | '/config/theme'
    | '/notifications/events'
    | '/pipeline/outputs'
    | '/sessions/$sessionId'
    | '/streamers/new'
    | '/system/health'
    | '/notifications'
    | '/pipeline'
    | '/player'
    | '/sessions'
    | '/streamers'
    | '/config/engines/$engineId'
    | '/config/engines/create'
    | '/config/platforms/$platformId'
    | '/config/templates/$templateId'
    | '/config/templates/create'
    | '/pipeline/executions/$pipelineId'
    | '/pipeline/jobs/$jobId'
    | '/pipeline/jobs/new'
    | '/pipeline/presets/$presetId'
    | '/pipeline/presets/create'
    | '/pipeline/workflows/$workflowId'
    | '/pipeline/workflows/create'
    | '/streamers/$id/edit'
    | '/config/engines'
    | '/config/platforms'
    | '/config/templates'
    | '/pipeline/jobs'
    | '/pipeline/presets'
    | '/pipeline/workflows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/stream-proxy'
    | '/change-password'
    | '/login'
    | '/config'
    | '/dashboard'
    | '/config/backup'
    | '/config/global'
    | '/config/language'
    | '/config/logging'
    | '/config/theme'
    | '/notifications/events'
    | '/pipeline/outputs'
    | '/sessions/$sessionId'
    | '/streamers/new'
    | '/system/health'
    | '/notifications'
    | '/pipeline'
    | '/player'
    | '/sessions'
    | '/streamers'
    | '/config/engines/$engineId'
    | '/config/engines/create'
    | '/config/platforms/$platformId'
    | '/config/templates/$templateId'
    | '/config/templates/create'
    | '/pipeline/executions/$pipelineId'
    | '/pipeline/jobs/$jobId'
    | '/pipeline/jobs/new'
    | '/pipeline/presets/$presetId'
    | '/pipeline/presets/create'
    | '/pipeline/workflows/$workflowId'
    | '/pipeline/workflows/create'
    | '/streamers/$id/edit'
    | '/config/engines'
    | '/config/platforms'
    | '/config/templates'
    | '/pipeline/jobs'
    | '/pipeline/presets'
    | '/pipeline/workflows'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_public'
    | '/logout'
    | '/stream-proxy'
    | '/_authed/_dashboard'
    | '/_authed/change-password'
    | '/_public/login'
    | '/_authed/_dashboard/config'
    | '/_authed/_dashboard/dashboard'
    | '/_authed/_dashboard/config/backup'
    | '/_authed/_dashboard/config/global'
    | '/_authed/_dashboard/config/language'
    | '/_authed/_dashboard/config/logging'
    | '/_authed/_dashboard/config/theme'
    | '/_authed/_dashboard/notifications/events'
    | '/_authed/_dashboard/pipeline/outputs'
    | '/_authed/_dashboard/sessions/$sessionId'
    | '/_authed/_dashboard/streamers/new'
    | '/_authed/_dashboard/system/health'
    | '/_authed/_dashboard/notifications/'
    | '/_authed/_dashboard/pipeline/'
    | '/_authed/_dashboard/player/'
    | '/_authed/_dashboard/sessions/'
    | '/_authed/_dashboard/streamers/'
    | '/_authed/_dashboard/config/engines/$engineId'
    | '/_authed/_dashboard/config/engines/create'
    | '/_authed/_dashboard/config/platforms/$platformId'
    | '/_authed/_dashboard/config/templates/$templateId'
    | '/_authed/_dashboard/config/templates/create'
    | '/_authed/_dashboard/pipeline/executions/$pipelineId'
    | '/_authed/_dashboard/pipeline/jobs/$jobId'
    | '/_authed/_dashboard/pipeline/jobs/new'
    | '/_authed/_dashboard/pipeline/presets/$presetId'
    | '/_authed/_dashboard/pipeline/presets/create'
    | '/_authed/_dashboard/pipeline/workflows/$workflowId'
    | '/_authed/_dashboard/pipeline/workflows/create'
    | '/_authed/_dashboard/streamers/$id/edit'
    | '/_authed/_dashboard/config/engines/'
    | '/_authed/_dashboard/config/platforms/'
    | '/_authed/_dashboard/config/templates/'
    | '/_authed/_dashboard/pipeline/jobs/'
    | '/_authed/_dashboard/pipeline/presets/'
    | '/_authed/_dashboard/pipeline/workflows/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  LogoutRoute: typeof LogoutRoute
  StreamProxyRoute: typeof StreamProxyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stream-proxy': {
      id: '/stream-proxy'
      path: '/stream-proxy'
      fullPath: '/stream-proxy'
      preLoaderRoute: typeof StreamProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authed/change-password': {
      id: '/_authed/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthedChangePasswordRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_dashboard': {
      id: '/_authed/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_dashboard/dashboard': {
      id: '/_authed/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardDashboardRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/config': {
      id: '/_authed/_dashboard/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AuthedDashboardConfigRouteRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/streamers/': {
      id: '/_authed/_dashboard/streamers/'
      path: '/streamers'
      fullPath: '/streamers'
      preLoaderRoute: typeof AuthedDashboardStreamersIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/sessions/': {
      id: '/_authed/_dashboard/sessions/'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthedDashboardSessionsIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/player/': {
      id: '/_authed/_dashboard/player/'
      path: '/player'
      fullPath: '/player'
      preLoaderRoute: typeof AuthedDashboardPlayerIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/pipeline/': {
      id: '/_authed/_dashboard/pipeline/'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthedDashboardPipelineIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/notifications/': {
      id: '/_authed/_dashboard/notifications/'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthedDashboardNotificationsIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/system/health': {
      id: '/_authed/_dashboard/system/health'
      path: '/system/health'
      fullPath: '/system/health'
      preLoaderRoute: typeof AuthedDashboardSystemHealthRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/streamers/new': {
      id: '/_authed/_dashboard/streamers/new'
      path: '/streamers/new'
      fullPath: '/streamers/new'
      preLoaderRoute: typeof AuthedDashboardStreamersNewRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/sessions/$sessionId': {
      id: '/_authed/_dashboard/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AuthedDashboardSessionsSessionIdRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/pipeline/outputs': {
      id: '/_authed/_dashboard/pipeline/outputs'
      path: '/pipeline/outputs'
      fullPath: '/pipeline/outputs'
      preLoaderRoute: typeof AuthedDashboardPipelineOutputsRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/notifications/events': {
      id: '/_authed/_dashboard/notifications/events'
      path: '/notifications/events'
      fullPath: '/notifications/events'
      preLoaderRoute: typeof AuthedDashboardNotificationsEventsRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/config/theme': {
      id: '/_authed/_dashboard/config/theme'
      path: '/theme'
      fullPath: '/config/theme'
      preLoaderRoute: typeof AuthedDashboardConfigThemeRouteImport
      parentRoute: typeof AuthedDashboardConfigRouteRoute
    }
    '/_authed/_dashboard/config/logging': {
      id: '/_authed/_dashboard/config/logging'
      path: '/logging'
      fullPath: '/config/logging'
      preLoaderRoute: typeof AuthedDashboardConfigLoggingRouteImport
      parentRoute: typeof AuthedDashboardConfigRouteRoute
    }
    '/_authed/_dashboard/config/language': {
      id: '/_authed/_dashboard/config/language'
      path: '/language'
      fullPath: '/config/language'
      preLoaderRoute: typeof AuthedDashboardConfigLanguageRouteImport
      parentRoute: typeof AuthedDashboardConfigRouteRoute
    }
    '/_authed/_dashboard/config/global': {
      id: '/_authed/_dashboard/config/global'
      path: '/global'
      fullPath: '/config/global'
      preLoaderRoute: typeof AuthedDashboardConfigGlobalRouteImport
      parentRoute: typeof AuthedDashboardConfigRouteRoute
    }
    '/_authed/_dashboard/config/backup': {
      id: '/_authed/_dashboard/config/backup'
      path: '/backup'
      fullPath: '/config/backup'
      preLoaderRoute: typeof AuthedDashboardConfigBackupRouteImport
      parentRoute: typeof AuthedDashboardConfigRouteRoute
    }
    '/_authed/_dashboard/pipeline/workflows/': {
      id: '/_authed/_dashboard/pipeline/workflows/'
      path: '/pipeline/workflows'
      fullPath: '/pipeline/workflows'
      preLoaderRoute: typeof AuthedDashboardPipelineWorkflowsIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/pipeline/presets/': {
      id: '/_authed/_dashboard/pipeline/presets/'
      path: '/pipeline/presets'
      fullPath: '/pipeline/presets'
      preLoaderRoute: typeof AuthedDashboardPipelinePresetsIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/pipeline/jobs/': {
      id: '/_authed/_dashboard/pipeline/jobs/'
      path: '/pipeline/jobs'
      fullPath: '/pipeline/jobs'
      preLoaderRoute: typeof AuthedDashboardPipelineJobsIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/config/templates/': {
      id: '/_authed/_dashboard/config/templates/'
      path: '/templates'
      fullPath: '/config/templates'
      preLoaderRoute: typeof AuthedDashboardConfigTemplatesIndexRouteImport
      parentRoute: typeof AuthedDashboardConfigRouteRoute
    }
    '/_authed/_dashboard/config/platforms/': {
      id: '/_authed/_dashboard/config/platforms/'
      path: '/platforms'
      fullPath: '/config/platforms'
      preLoaderRoute: typeof AuthedDashboardConfigPlatformsIndexRouteImport
      parentRoute: typeof AuthedDashboardConfigRouteRoute
    }
    '/_authed/_dashboard/config/engines/': {
      id: '/_authed/_dashboard/config/engines/'
      path: '/engines'
      fullPath: '/config/engines'
      preLoaderRoute: typeof AuthedDashboardConfigEnginesIndexRouteImport
      parentRoute: typeof AuthedDashboardConfigRouteRoute
    }
    '/_authed/_dashboard/streamers/$id/edit': {
      id: '/_authed/_dashboard/streamers/$id/edit'
      path: '/streamers/$id/edit'
      fullPath: '/streamers/$id/edit'
      preLoaderRoute: typeof AuthedDashboardStreamersIdEditRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/pipeline/workflows/create': {
      id: '/_authed/_dashboard/pipeline/workflows/create'
      path: '/pipeline/workflows/create'
      fullPath: '/pipeline/workflows/create'
      preLoaderRoute: typeof AuthedDashboardPipelineWorkflowsCreateRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/pipeline/workflows/$workflowId': {
      id: '/_authed/_dashboard/pipeline/workflows/$workflowId'
      path: '/pipeline/workflows/$workflowId'
      fullPath: '/pipeline/workflows/$workflowId'
      preLoaderRoute: typeof AuthedDashboardPipelineWorkflowsWorkflowIdRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/pipeline/presets/create': {
      id: '/_authed/_dashboard/pipeline/presets/create'
      path: '/pipeline/presets/create'
      fullPath: '/pipeline/presets/create'
      preLoaderRoute: typeof AuthedDashboardPipelinePresetsCreateRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/pipeline/presets/$presetId': {
      id: '/_authed/_dashboard/pipeline/presets/$presetId'
      path: '/pipeline/presets/$presetId'
      fullPath: '/pipeline/presets/$presetId'
      preLoaderRoute: typeof AuthedDashboardPipelinePresetsPresetIdRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/pipeline/jobs/new': {
      id: '/_authed/_dashboard/pipeline/jobs/new'
      path: '/pipeline/jobs/new'
      fullPath: '/pipeline/jobs/new'
      preLoaderRoute: typeof AuthedDashboardPipelineJobsNewRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/pipeline/jobs/$jobId': {
      id: '/_authed/_dashboard/pipeline/jobs/$jobId'
      path: '/pipeline/jobs/$jobId'
      fullPath: '/pipeline/jobs/$jobId'
      preLoaderRoute: typeof AuthedDashboardPipelineJobsJobIdRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/pipeline/executions/$pipelineId': {
      id: '/_authed/_dashboard/pipeline/executions/$pipelineId'
      path: '/pipeline/executions/$pipelineId'
      fullPath: '/pipeline/executions/$pipelineId'
      preLoaderRoute: typeof AuthedDashboardPipelineExecutionsPipelineIdRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/config/templates/create': {
      id: '/_authed/_dashboard/config/templates/create'
      path: '/templates/create'
      fullPath: '/config/templates/create'
      preLoaderRoute: typeof AuthedDashboardConfigTemplatesCreateRouteImport
      parentRoute: typeof AuthedDashboardConfigRouteRoute
    }
    '/_authed/_dashboard/config/templates/$templateId': {
      id: '/_authed/_dashboard/config/templates/$templateId'
      path: '/templates/$templateId'
      fullPath: '/config/templates/$templateId'
      preLoaderRoute: typeof AuthedDashboardConfigTemplatesTemplateIdRouteImport
      parentRoute: typeof AuthedDashboardConfigRouteRoute
    }
    '/_authed/_dashboard/config/platforms/$platformId': {
      id: '/_authed/_dashboard/config/platforms/$platformId'
      path: '/platforms/$platformId'
      fullPath: '/config/platforms/$platformId'
      preLoaderRoute: typeof AuthedDashboardConfigPlatformsPlatformIdRouteImport
      parentRoute: typeof AuthedDashboardConfigRouteRoute
    }
    '/_authed/_dashboard/config/engines/create': {
      id: '/_authed/_dashboard/config/engines/create'
      path: '/engines/create'
      fullPath: '/config/engines/create'
      preLoaderRoute: typeof AuthedDashboardConfigEnginesCreateRouteImport
      parentRoute: typeof AuthedDashboardConfigRouteRoute
    }
    '/_authed/_dashboard/config/engines/$engineId': {
      id: '/_authed/_dashboard/config/engines/$engineId'
      path: '/engines/$engineId'
      fullPath: '/config/engines/$engineId'
      preLoaderRoute: typeof AuthedDashboardConfigEnginesEngineIdRouteImport
      parentRoute: typeof AuthedDashboardConfigRouteRoute
    }
  }
}

interface AuthedDashboardConfigRouteRouteChildren {
  AuthedDashboardConfigBackupRoute: typeof AuthedDashboardConfigBackupRoute
  AuthedDashboardConfigGlobalRoute: typeof AuthedDashboardConfigGlobalRoute
  AuthedDashboardConfigLanguageRoute: typeof AuthedDashboardConfigLanguageRoute
  AuthedDashboardConfigLoggingRoute: typeof AuthedDashboardConfigLoggingRoute
  AuthedDashboardConfigThemeRoute: typeof AuthedDashboardConfigThemeRoute
  AuthedDashboardConfigEnginesEngineIdRoute: typeof AuthedDashboardConfigEnginesEngineIdRoute
  AuthedDashboardConfigEnginesCreateRoute: typeof AuthedDashboardConfigEnginesCreateRoute
  AuthedDashboardConfigPlatformsPlatformIdRoute: typeof AuthedDashboardConfigPlatformsPlatformIdRoute
  AuthedDashboardConfigTemplatesTemplateIdRoute: typeof AuthedDashboardConfigTemplatesTemplateIdRoute
  AuthedDashboardConfigTemplatesCreateRoute: typeof AuthedDashboardConfigTemplatesCreateRoute
  AuthedDashboardConfigEnginesIndexRoute: typeof AuthedDashboardConfigEnginesIndexRoute
  AuthedDashboardConfigPlatformsIndexRoute: typeof AuthedDashboardConfigPlatformsIndexRoute
  AuthedDashboardConfigTemplatesIndexRoute: typeof AuthedDashboardConfigTemplatesIndexRoute
}

const AuthedDashboardConfigRouteRouteChildren: AuthedDashboardConfigRouteRouteChildren =
  {
    AuthedDashboardConfigBackupRoute: AuthedDashboardConfigBackupRoute,
    AuthedDashboardConfigGlobalRoute: AuthedDashboardConfigGlobalRoute,
    AuthedDashboardConfigLanguageRoute: AuthedDashboardConfigLanguageRoute,
    AuthedDashboardConfigLoggingRoute: AuthedDashboardConfigLoggingRoute,
    AuthedDashboardConfigThemeRoute: AuthedDashboardConfigThemeRoute,
    AuthedDashboardConfigEnginesEngineIdRoute:
      AuthedDashboardConfigEnginesEngineIdRoute,
    AuthedDashboardConfigEnginesCreateRoute:
      AuthedDashboardConfigEnginesCreateRoute,
    AuthedDashboardConfigPlatformsPlatformIdRoute:
      AuthedDashboardConfigPlatformsPlatformIdRoute,
    AuthedDashboardConfigTemplatesTemplateIdRoute:
      AuthedDashboardConfigTemplatesTemplateIdRoute,
    AuthedDashboardConfigTemplatesCreateRoute:
      AuthedDashboardConfigTemplatesCreateRoute,
    AuthedDashboardConfigEnginesIndexRoute:
      AuthedDashboardConfigEnginesIndexRoute,
    AuthedDashboardConfigPlatformsIndexRoute:
      AuthedDashboardConfigPlatformsIndexRoute,
    AuthedDashboardConfigTemplatesIndexRoute:
      AuthedDashboardConfigTemplatesIndexRoute,
  }

const AuthedDashboardConfigRouteRouteWithChildren =
  AuthedDashboardConfigRouteRoute._addFileChildren(
    AuthedDashboardConfigRouteRouteChildren,
  )

interface AuthedDashboardRouteChildren {
  AuthedDashboardConfigRouteRoute: typeof AuthedDashboardConfigRouteRouteWithChildren
  AuthedDashboardDashboardRoute: typeof AuthedDashboardDashboardRoute
  AuthedDashboardNotificationsEventsRoute: typeof AuthedDashboardNotificationsEventsRoute
  AuthedDashboardPipelineOutputsRoute: typeof AuthedDashboardPipelineOutputsRoute
  AuthedDashboardSessionsSessionIdRoute: typeof AuthedDashboardSessionsSessionIdRoute
  AuthedDashboardStreamersNewRoute: typeof AuthedDashboardStreamersNewRoute
  AuthedDashboardSystemHealthRoute: typeof AuthedDashboardSystemHealthRoute
  AuthedDashboardNotificationsIndexRoute: typeof AuthedDashboardNotificationsIndexRoute
  AuthedDashboardPipelineIndexRoute: typeof AuthedDashboardPipelineIndexRoute
  AuthedDashboardPlayerIndexRoute: typeof AuthedDashboardPlayerIndexRoute
  AuthedDashboardSessionsIndexRoute: typeof AuthedDashboardSessionsIndexRoute
  AuthedDashboardStreamersIndexRoute: typeof AuthedDashboardStreamersIndexRoute
  AuthedDashboardPipelineExecutionsPipelineIdRoute: typeof AuthedDashboardPipelineExecutionsPipelineIdRoute
  AuthedDashboardPipelineJobsJobIdRoute: typeof AuthedDashboardPipelineJobsJobIdRoute
  AuthedDashboardPipelineJobsNewRoute: typeof AuthedDashboardPipelineJobsNewRoute
  AuthedDashboardPipelinePresetsPresetIdRoute: typeof AuthedDashboardPipelinePresetsPresetIdRoute
  AuthedDashboardPipelinePresetsCreateRoute: typeof AuthedDashboardPipelinePresetsCreateRoute
  AuthedDashboardPipelineWorkflowsWorkflowIdRoute: typeof AuthedDashboardPipelineWorkflowsWorkflowIdRoute
  AuthedDashboardPipelineWorkflowsCreateRoute: typeof AuthedDashboardPipelineWorkflowsCreateRoute
  AuthedDashboardStreamersIdEditRoute: typeof AuthedDashboardStreamersIdEditRoute
  AuthedDashboardPipelineJobsIndexRoute: typeof AuthedDashboardPipelineJobsIndexRoute
  AuthedDashboardPipelinePresetsIndexRoute: typeof AuthedDashboardPipelinePresetsIndexRoute
  AuthedDashboardPipelineWorkflowsIndexRoute: typeof AuthedDashboardPipelineWorkflowsIndexRoute
}

const AuthedDashboardRouteChildren: AuthedDashboardRouteChildren = {
  AuthedDashboardConfigRouteRoute: AuthedDashboardConfigRouteRouteWithChildren,
  AuthedDashboardDashboardRoute: AuthedDashboardDashboardRoute,
  AuthedDashboardNotificationsEventsRoute:
    AuthedDashboardNotificationsEventsRoute,
  AuthedDashboardPipelineOutputsRoute: AuthedDashboardPipelineOutputsRoute,
  AuthedDashboardSessionsSessionIdRoute: AuthedDashboardSessionsSessionIdRoute,
  AuthedDashboardStreamersNewRoute: AuthedDashboardStreamersNewRoute,
  AuthedDashboardSystemHealthRoute: AuthedDashboardSystemHealthRoute,
  AuthedDashboardNotificationsIndexRoute:
    AuthedDashboardNotificationsIndexRoute,
  AuthedDashboardPipelineIndexRoute: AuthedDashboardPipelineIndexRoute,
  AuthedDashboardPlayerIndexRoute: AuthedDashboardPlayerIndexRoute,
  AuthedDashboardSessionsIndexRoute: AuthedDashboardSessionsIndexRoute,
  AuthedDashboardStreamersIndexRoute: AuthedDashboardStreamersIndexRoute,
  AuthedDashboardPipelineExecutionsPipelineIdRoute:
    AuthedDashboardPipelineExecutionsPipelineIdRoute,
  AuthedDashboardPipelineJobsJobIdRoute: AuthedDashboardPipelineJobsJobIdRoute,
  AuthedDashboardPipelineJobsNewRoute: AuthedDashboardPipelineJobsNewRoute,
  AuthedDashboardPipelinePresetsPresetIdRoute:
    AuthedDashboardPipelinePresetsPresetIdRoute,
  AuthedDashboardPipelinePresetsCreateRoute:
    AuthedDashboardPipelinePresetsCreateRoute,
  AuthedDashboardPipelineWorkflowsWorkflowIdRoute:
    AuthedDashboardPipelineWorkflowsWorkflowIdRoute,
  AuthedDashboardPipelineWorkflowsCreateRoute:
    AuthedDashboardPipelineWorkflowsCreateRoute,
  AuthedDashboardStreamersIdEditRoute: AuthedDashboardStreamersIdEditRoute,
  AuthedDashboardPipelineJobsIndexRoute: AuthedDashboardPipelineJobsIndexRoute,
  AuthedDashboardPipelinePresetsIndexRoute:
    AuthedDashboardPipelinePresetsIndexRoute,
  AuthedDashboardPipelineWorkflowsIndexRoute:
    AuthedDashboardPipelineWorkflowsIndexRoute,
}

const AuthedDashboardRouteWithChildren = AuthedDashboardRoute._addFileChildren(
  AuthedDashboardRouteChildren,
)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRouteWithChildren
  AuthedChangePasswordRoute: typeof AuthedChangePasswordRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRouteWithChildren,
  AuthedChangePasswordRoute: AuthedChangePasswordRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  LogoutRoute: LogoutRoute,
  StreamProxyRoute: StreamProxyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
