/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as AuthedChangePasswordRouteImport } from './routes/_authed/change-password'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/_dashboard'
import { Route as AuthedDashboardDashboardRouteImport } from './routes/_authed/_dashboard/dashboard'
import { Route as AuthedDashboardConfigRouteRouteImport } from './routes/_authed/_dashboard/config/route'
import { Route as AuthedDashboardStreamersIndexRouteImport } from './routes/_authed/_dashboard/streamers/index'
import { Route as AuthedDashboardSessionsIndexRouteImport } from './routes/_authed/_dashboard/sessions/index'
import { Route as AuthedDashboardStreamersNewRouteImport } from './routes/_authed/_dashboard/streamers/new'
import { Route as AuthedDashboardSessionsSessionIdRouteImport } from './routes/_authed/_dashboard/sessions/$sessionId'
import { Route as AuthedDashboardPipelineOutputsRouteImport } from './routes/_authed/_dashboard/pipeline/outputs'
import { Route as AuthedDashboardPipelineJobsRouteImport } from './routes/_authed/_dashboard/pipeline/jobs'
import { Route as AuthedDashboardConfigThemeRouteImport } from './routes/_authed/_dashboard/config/theme'
import { Route as AuthedDashboardConfigTemplatesRouteImport } from './routes/_authed/_dashboard/config/templates'
import { Route as AuthedDashboardConfigPlatformsRouteImport } from './routes/_authed/_dashboard/config/platforms'
import { Route as AuthedDashboardConfigGlobalRouteImport } from './routes/_authed/_dashboard/config/global'
import { Route as AuthedDashboardConfigEnginesRouteImport } from './routes/_authed/_dashboard/config/engines'
import { Route as AuthedDashboardStreamersIdEditRouteImport } from './routes/_authed/_dashboard/streamers/$id.edit'

const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const AuthedChangePasswordRoute = AuthedChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardDashboardRoute =
  AuthedDashboardDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardConfigRouteRoute =
  AuthedDashboardConfigRouteRouteImport.update({
    id: '/config',
    path: '/config',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardStreamersIndexRoute =
  AuthedDashboardStreamersIndexRouteImport.update({
    id: '/streamers/',
    path: '/streamers/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardSessionsIndexRoute =
  AuthedDashboardSessionsIndexRouteImport.update({
    id: '/sessions/',
    path: '/sessions/',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardStreamersNewRoute =
  AuthedDashboardStreamersNewRouteImport.update({
    id: '/streamers/new',
    path: '/streamers/new',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardSessionsSessionIdRoute =
  AuthedDashboardSessionsSessionIdRouteImport.update({
    id: '/sessions/$sessionId',
    path: '/sessions/$sessionId',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardPipelineOutputsRoute =
  AuthedDashboardPipelineOutputsRouteImport.update({
    id: '/pipeline/outputs',
    path: '/pipeline/outputs',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardPipelineJobsRoute =
  AuthedDashboardPipelineJobsRouteImport.update({
    id: '/pipeline/jobs',
    path: '/pipeline/jobs',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)
const AuthedDashboardConfigThemeRoute =
  AuthedDashboardConfigThemeRouteImport.update({
    id: '/theme',
    path: '/theme',
    getParentRoute: () => AuthedDashboardConfigRouteRoute,
  } as any)
const AuthedDashboardConfigTemplatesRoute =
  AuthedDashboardConfigTemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => AuthedDashboardConfigRouteRoute,
  } as any)
const AuthedDashboardConfigPlatformsRoute =
  AuthedDashboardConfigPlatformsRouteImport.update({
    id: '/platforms',
    path: '/platforms',
    getParentRoute: () => AuthedDashboardConfigRouteRoute,
  } as any)
const AuthedDashboardConfigGlobalRoute =
  AuthedDashboardConfigGlobalRouteImport.update({
    id: '/global',
    path: '/global',
    getParentRoute: () => AuthedDashboardConfigRouteRoute,
  } as any)
const AuthedDashboardConfigEnginesRoute =
  AuthedDashboardConfigEnginesRouteImport.update({
    id: '/engines',
    path: '/engines',
    getParentRoute: () => AuthedDashboardConfigRouteRoute,
  } as any)
const AuthedDashboardStreamersIdEditRoute =
  AuthedDashboardStreamersIdEditRouteImport.update({
    id: '/streamers/$id/edit',
    path: '/streamers/$id/edit',
    getParentRoute: () => AuthedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/change-password': typeof AuthedChangePasswordRoute
  '/login': typeof PublicLoginRoute
  '/config': typeof AuthedDashboardConfigRouteRouteWithChildren
  '/dashboard': typeof AuthedDashboardDashboardRoute
  '/config/engines': typeof AuthedDashboardConfigEnginesRoute
  '/config/global': typeof AuthedDashboardConfigGlobalRoute
  '/config/platforms': typeof AuthedDashboardConfigPlatformsRoute
  '/config/templates': typeof AuthedDashboardConfigTemplatesRoute
  '/config/theme': typeof AuthedDashboardConfigThemeRoute
  '/pipeline/jobs': typeof AuthedDashboardPipelineJobsRoute
  '/pipeline/outputs': typeof AuthedDashboardPipelineOutputsRoute
  '/sessions/$sessionId': typeof AuthedDashboardSessionsSessionIdRoute
  '/streamers/new': typeof AuthedDashboardStreamersNewRoute
  '/sessions': typeof AuthedDashboardSessionsIndexRoute
  '/streamers': typeof AuthedDashboardStreamersIndexRoute
  '/streamers/$id/edit': typeof AuthedDashboardStreamersIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/logout': typeof LogoutRoute
  '/change-password': typeof AuthedChangePasswordRoute
  '/login': typeof PublicLoginRoute
  '/config': typeof AuthedDashboardConfigRouteRouteWithChildren
  '/dashboard': typeof AuthedDashboardDashboardRoute
  '/config/engines': typeof AuthedDashboardConfigEnginesRoute
  '/config/global': typeof AuthedDashboardConfigGlobalRoute
  '/config/platforms': typeof AuthedDashboardConfigPlatformsRoute
  '/config/templates': typeof AuthedDashboardConfigTemplatesRoute
  '/config/theme': typeof AuthedDashboardConfigThemeRoute
  '/pipeline/jobs': typeof AuthedDashboardPipelineJobsRoute
  '/pipeline/outputs': typeof AuthedDashboardPipelineOutputsRoute
  '/sessions/$sessionId': typeof AuthedDashboardSessionsSessionIdRoute
  '/streamers/new': typeof AuthedDashboardStreamersNewRoute
  '/sessions': typeof AuthedDashboardSessionsIndexRoute
  '/streamers': typeof AuthedDashboardStreamersIndexRoute
  '/streamers/$id/edit': typeof AuthedDashboardStreamersIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/logout': typeof LogoutRoute
  '/_authed/_dashboard': typeof AuthedDashboardRouteWithChildren
  '/_authed/change-password': typeof AuthedChangePasswordRoute
  '/_public/login': typeof PublicLoginRoute
  '/_authed/_dashboard/config': typeof AuthedDashboardConfigRouteRouteWithChildren
  '/_authed/_dashboard/dashboard': typeof AuthedDashboardDashboardRoute
  '/_authed/_dashboard/config/engines': typeof AuthedDashboardConfigEnginesRoute
  '/_authed/_dashboard/config/global': typeof AuthedDashboardConfigGlobalRoute
  '/_authed/_dashboard/config/platforms': typeof AuthedDashboardConfigPlatformsRoute
  '/_authed/_dashboard/config/templates': typeof AuthedDashboardConfigTemplatesRoute
  '/_authed/_dashboard/config/theme': typeof AuthedDashboardConfigThemeRoute
  '/_authed/_dashboard/pipeline/jobs': typeof AuthedDashboardPipelineJobsRoute
  '/_authed/_dashboard/pipeline/outputs': typeof AuthedDashboardPipelineOutputsRoute
  '/_authed/_dashboard/sessions/$sessionId': typeof AuthedDashboardSessionsSessionIdRoute
  '/_authed/_dashboard/streamers/new': typeof AuthedDashboardStreamersNewRoute
  '/_authed/_dashboard/sessions/': typeof AuthedDashboardSessionsIndexRoute
  '/_authed/_dashboard/streamers/': typeof AuthedDashboardStreamersIndexRoute
  '/_authed/_dashboard/streamers/$id/edit': typeof AuthedDashboardStreamersIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/logout'
    | '/change-password'
    | '/login'
    | '/config'
    | '/dashboard'
    | '/config/engines'
    | '/config/global'
    | '/config/platforms'
    | '/config/templates'
    | '/config/theme'
    | '/pipeline/jobs'
    | '/pipeline/outputs'
    | '/sessions/$sessionId'
    | '/streamers/new'
    | '/sessions'
    | '/streamers'
    | '/streamers/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/logout'
    | '/change-password'
    | '/login'
    | '/config'
    | '/dashboard'
    | '/config/engines'
    | '/config/global'
    | '/config/platforms'
    | '/config/templates'
    | '/config/theme'
    | '/pipeline/jobs'
    | '/pipeline/outputs'
    | '/sessions/$sessionId'
    | '/streamers/new'
    | '/sessions'
    | '/streamers'
    | '/streamers/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/_public'
    | '/logout'
    | '/_authed/_dashboard'
    | '/_authed/change-password'
    | '/_public/login'
    | '/_authed/_dashboard/config'
    | '/_authed/_dashboard/dashboard'
    | '/_authed/_dashboard/config/engines'
    | '/_authed/_dashboard/config/global'
    | '/_authed/_dashboard/config/platforms'
    | '/_authed/_dashboard/config/templates'
    | '/_authed/_dashboard/config/theme'
    | '/_authed/_dashboard/pipeline/jobs'
    | '/_authed/_dashboard/pipeline/outputs'
    | '/_authed/_dashboard/sessions/$sessionId'
    | '/_authed/_dashboard/streamers/new'
    | '/_authed/_dashboard/sessions/'
    | '/_authed/_dashboard/streamers/'
    | '/_authed/_dashboard/streamers/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  LogoutRoute: typeof LogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_authed/change-password': {
      id: '/_authed/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthedChangePasswordRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_dashboard': {
      id: '/_authed/_dashboard'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/_dashboard/dashboard': {
      id: '/_authed/_dashboard/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardDashboardRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/config': {
      id: '/_authed/_dashboard/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof AuthedDashboardConfigRouteRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/streamers/': {
      id: '/_authed/_dashboard/streamers/'
      path: '/streamers'
      fullPath: '/streamers'
      preLoaderRoute: typeof AuthedDashboardStreamersIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/sessions/': {
      id: '/_authed/_dashboard/sessions/'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof AuthedDashboardSessionsIndexRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/streamers/new': {
      id: '/_authed/_dashboard/streamers/new'
      path: '/streamers/new'
      fullPath: '/streamers/new'
      preLoaderRoute: typeof AuthedDashboardStreamersNewRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/sessions/$sessionId': {
      id: '/_authed/_dashboard/sessions/$sessionId'
      path: '/sessions/$sessionId'
      fullPath: '/sessions/$sessionId'
      preLoaderRoute: typeof AuthedDashboardSessionsSessionIdRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/pipeline/outputs': {
      id: '/_authed/_dashboard/pipeline/outputs'
      path: '/pipeline/outputs'
      fullPath: '/pipeline/outputs'
      preLoaderRoute: typeof AuthedDashboardPipelineOutputsRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/pipeline/jobs': {
      id: '/_authed/_dashboard/pipeline/jobs'
      path: '/pipeline/jobs'
      fullPath: '/pipeline/jobs'
      preLoaderRoute: typeof AuthedDashboardPipelineJobsRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
    '/_authed/_dashboard/config/theme': {
      id: '/_authed/_dashboard/config/theme'
      path: '/theme'
      fullPath: '/config/theme'
      preLoaderRoute: typeof AuthedDashboardConfigThemeRouteImport
      parentRoute: typeof AuthedDashboardConfigRouteRoute
    }
    '/_authed/_dashboard/config/templates': {
      id: '/_authed/_dashboard/config/templates'
      path: '/templates'
      fullPath: '/config/templates'
      preLoaderRoute: typeof AuthedDashboardConfigTemplatesRouteImport
      parentRoute: typeof AuthedDashboardConfigRouteRoute
    }
    '/_authed/_dashboard/config/platforms': {
      id: '/_authed/_dashboard/config/platforms'
      path: '/platforms'
      fullPath: '/config/platforms'
      preLoaderRoute: typeof AuthedDashboardConfigPlatformsRouteImport
      parentRoute: typeof AuthedDashboardConfigRouteRoute
    }
    '/_authed/_dashboard/config/global': {
      id: '/_authed/_dashboard/config/global'
      path: '/global'
      fullPath: '/config/global'
      preLoaderRoute: typeof AuthedDashboardConfigGlobalRouteImport
      parentRoute: typeof AuthedDashboardConfigRouteRoute
    }
    '/_authed/_dashboard/config/engines': {
      id: '/_authed/_dashboard/config/engines'
      path: '/engines'
      fullPath: '/config/engines'
      preLoaderRoute: typeof AuthedDashboardConfigEnginesRouteImport
      parentRoute: typeof AuthedDashboardConfigRouteRoute
    }
    '/_authed/_dashboard/streamers/$id/edit': {
      id: '/_authed/_dashboard/streamers/$id/edit'
      path: '/streamers/$id/edit'
      fullPath: '/streamers/$id/edit'
      preLoaderRoute: typeof AuthedDashboardStreamersIdEditRouteImport
      parentRoute: typeof AuthedDashboardRoute
    }
  }
}

interface AuthedDashboardConfigRouteRouteChildren {
  AuthedDashboardConfigEnginesRoute: typeof AuthedDashboardConfigEnginesRoute
  AuthedDashboardConfigGlobalRoute: typeof AuthedDashboardConfigGlobalRoute
  AuthedDashboardConfigPlatformsRoute: typeof AuthedDashboardConfigPlatformsRoute
  AuthedDashboardConfigTemplatesRoute: typeof AuthedDashboardConfigTemplatesRoute
  AuthedDashboardConfigThemeRoute: typeof AuthedDashboardConfigThemeRoute
}

const AuthedDashboardConfigRouteRouteChildren: AuthedDashboardConfigRouteRouteChildren =
  {
    AuthedDashboardConfigEnginesRoute: AuthedDashboardConfigEnginesRoute,
    AuthedDashboardConfigGlobalRoute: AuthedDashboardConfigGlobalRoute,
    AuthedDashboardConfigPlatformsRoute: AuthedDashboardConfigPlatformsRoute,
    AuthedDashboardConfigTemplatesRoute: AuthedDashboardConfigTemplatesRoute,
    AuthedDashboardConfigThemeRoute: AuthedDashboardConfigThemeRoute,
  }

const AuthedDashboardConfigRouteRouteWithChildren =
  AuthedDashboardConfigRouteRoute._addFileChildren(
    AuthedDashboardConfigRouteRouteChildren,
  )

interface AuthedDashboardRouteChildren {
  AuthedDashboardConfigRouteRoute: typeof AuthedDashboardConfigRouteRouteWithChildren
  AuthedDashboardDashboardRoute: typeof AuthedDashboardDashboardRoute
  AuthedDashboardPipelineJobsRoute: typeof AuthedDashboardPipelineJobsRoute
  AuthedDashboardPipelineOutputsRoute: typeof AuthedDashboardPipelineOutputsRoute
  AuthedDashboardSessionsSessionIdRoute: typeof AuthedDashboardSessionsSessionIdRoute
  AuthedDashboardStreamersNewRoute: typeof AuthedDashboardStreamersNewRoute
  AuthedDashboardSessionsIndexRoute: typeof AuthedDashboardSessionsIndexRoute
  AuthedDashboardStreamersIndexRoute: typeof AuthedDashboardStreamersIndexRoute
  AuthedDashboardStreamersIdEditRoute: typeof AuthedDashboardStreamersIdEditRoute
}

const AuthedDashboardRouteChildren: AuthedDashboardRouteChildren = {
  AuthedDashboardConfigRouteRoute: AuthedDashboardConfigRouteRouteWithChildren,
  AuthedDashboardDashboardRoute: AuthedDashboardDashboardRoute,
  AuthedDashboardPipelineJobsRoute: AuthedDashboardPipelineJobsRoute,
  AuthedDashboardPipelineOutputsRoute: AuthedDashboardPipelineOutputsRoute,
  AuthedDashboardSessionsSessionIdRoute: AuthedDashboardSessionsSessionIdRoute,
  AuthedDashboardStreamersNewRoute: AuthedDashboardStreamersNewRoute,
  AuthedDashboardSessionsIndexRoute: AuthedDashboardSessionsIndexRoute,
  AuthedDashboardStreamersIndexRoute: AuthedDashboardStreamersIndexRoute,
  AuthedDashboardStreamersIdEditRoute: AuthedDashboardStreamersIdEditRoute,
}

const AuthedDashboardRouteWithChildren = AuthedDashboardRoute._addFileChildren(
  AuthedDashboardRouteChildren,
)

interface AuthedRouteChildren {
  AuthedDashboardRoute: typeof AuthedDashboardRouteWithChildren
  AuthedChangePasswordRoute: typeof AuthedChangePasswordRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedDashboardRoute: AuthedDashboardRouteWithChildren,
  AuthedChangePasswordRoute: AuthedChangePasswordRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface PublicRouteChildren {
  PublicLoginRoute: typeof PublicLoginRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicLoginRoute: PublicLoginRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  LogoutRoute: LogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
