name: Feature request
description: Suggest an improvement or new feature.
title: "feat: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Please describe the problem first, then the solution you have in mind.

        If you include logs, screenshots, or config snippets, please **redact secrets** (tokens, cookies, stream keys, passwords, private URLs).

  - type: checkboxes
    id: safety
    attributes:
      label: Safety / privacy
      options:
        - label: I confirm I removed or masked secrets and sensitive data from the issue content
          required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part would this change affect?
      options:
        - Backend (rust-srec)
        - Web UI (rust-srec/frontend)
        - Desktop (rust-srec/src-tauri)
        - CLI (strev)
        - CLI (mesio)
        - Workspace crate (crates/*)
        - Docker / deployment
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What are you trying to do, and what is painful today?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to see happen?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Other approaches or workarounds you've tried.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Mockups, screenshots, related links, etc.
    validations:
      required: false
