name: Rust CI

on:
  push:
    branches: [main, dev]
    tags:
      - "v*"
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Check
        run: cargo check --workspace

  test:
    name: Test Suite
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04-arm, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test --workspace

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Clippy check
        run: cargo clippy --all-targets --all-features -- -D warnings

  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-22.04-arm, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: siphon
            asset_name: siphon-linux-amd64
          - os: ubuntu-22.04-arm
            artifact_name: siphon
            asset_name: siphon-linux-arm64
          - os: windows-latest
            artifact_name: siphon.exe
            asset_name: siphon-windows-amd64.exe
          - os: macos-latest
            artifact_name: siphon
            asset_name: siphon-macos-amd64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Build release
        run: cargo build -p siphon --release
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: target/release/${{ matrix.artifact_name }}
          if-no-files-found: error

  release:
    name: Release
    needs: [check, test, clippy, build]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: List artifacts
        run: ls -R artifacts

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            artifacts/siphon-linux-amd64/siphon
            artifacts/siphon-linux-arm64/siphon
            artifacts/siphon-windows-amd64.exe/siphon.exe
            artifacts/siphon-macos-amd64/siphon
          draft: false
          prerelease: false
