[package]
name = "aac"
version = "0.1.1"
edition = "2024"

[dependencies]
num-traits = "0.2"
num-derive = "0.4"
bytes-util = { path = "../bytes-util" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage_nightly)'] }
